"""
Tests for tools/scaffold.py - `fha install` and `fha update-tools` (BUILD.md M9).

Two layers:
  1. A manifest-sync guard that recomputes the operating-layer manifest from the
     real repo and asserts the committed manifest.json still matches it - so a PR
     that changes a tool/doc/skeleton file but forgets to regenerate fails here.
  2. Behavior tests against a small, hand-built FAKE repo (no .git/, proving the
     git-free / zip install path) and throwaway archives, exercising install,
     re-install refusal, the four update outcomes (add/stock/customized/retired),
     the critical skeleton-is-never-touched safety property, dry-run no-ops, and
     the friendly error paths.

Run: python -m unittest tests.test_scaffold -v
"""

import argparse
import contextlib
import io
import json
import os
import pathlib
import shlex
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'tools'))

import scaffold
from _lib import EXIT_CLEAN, EXIT_FAILURE, EXIT_WARNINGS


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='utf-8')


def _make_fake_repo(repo: Path) -> Path:
    """Build a minimal public-repo clone: 3 operating files + 3 skeleton seeds.

    Deliberately tiny so the tests are fast and every file's role is obvious. No
    .git/ is created anywhere - install/update working against this directory is
    itself the proof of the zip-based, git-free path (BUILD.md M9.1).
    """
    _write(repo / 'SPEC.md', '# SPEC\n\n**Version 9.9 - 2026-01-01**\n\nbody\n')
    _write(repo / 'tools' / 'atool.py', 'print("a tool")\n')
    _write(repo / 'docs' / 'guide.md', '# Guide\n')
    # bytecode that must NOT enter the manifest
    _write(repo / 'tools' / '__pycache__' / 'atool.cpython-312.pyc', 'junk\n')
    # skeleton (remapped from archive-template/ → archive root)
    _write(repo / 'archive-template' / 'fha.yaml', 'roots:\n  photos: photos\n')
    _write(repo / 'archive-template' / 'places' / 'places.yaml', '# places\n')
    _write(repo / 'archive-template' / 'sources' / '.gitkeep', '')
    _write(repo / 'archive-template' / 'README.md', 'template readme - excluded\n')
    # The install-once skeleton override that lives UNDER an operating subtree,
    # so it is the one seed whose archive path moves with the vendor layout.
    _write(repo / 'design' / 'custom.css', '/* stock */\n')
    scaffold._write_manifest(repo)
    return repo


class ManifestSyncTest(unittest.TestCase):
    """The committed manifest.json must match what the repo currently contains."""

    @unittest.skipIf(sys.platform == 'win32',
                     'git core.autocrlf rewrites tracked LF files (e.g. '
                     'design/custom.css, serve.cmd) to CRLF on a Windows '
                     'checkout, so regenerated byte-hashes differ from the '
                     'LF-based committed manifest; CI (Linux) checks currency.')
    def test_committed_manifest_is_current(self):
        committed = json.loads((ROOT / 'manifest.json').read_text(encoding='utf-8'))
        regenerated = scaffold.generate_manifest(ROOT)
        # `generated` is a date stamp that legitimately changes day to day; the
        # contract is the file set + checksums + versions.
        self.assertEqual(committed['manifest_version'], regenerated['manifest_version'])
        self.assertEqual(committed['spec_version'], regenerated['spec_version'])
        self.assertEqual(
            committed['files'], regenerated['files'],
            'manifest.json is out of date - run '
            '`python tools/scaffold.py write-manifest --repo .` and commit the result.',
        )

    def test_manifest_excludes_repo_furniture(self):
        paths = {e['path'] for e in scaffold.generate_manifest(ROOT)['files']}
        # Public-repo furniture that must never enter an archive: PRIVACY.md is the
        # "no real data" policy (contradictory inside a real archive), and the
        # release checklist / packing list / template's own readme are spec-repo
        # maintenance.
        for furniture in ('PRIVACY.md', 'RELEASE_CHECKLIST.md',
                          'manifest.json', 'archive-template/README.md'):
            self.assertNotIn(furniture, paths)
        # No bytecode, no example/test furniture.
        self.assertFalse(any('__pycache__' in p or p.endswith('.pyc') for p in paths))
        self.assertFalse(any(p.startswith(('example-archive/', 'tests/', 'archive-template/'))
                             for p in paths))

    def test_manifest_includes_operating_extras(self):
        paths = {e['path'] for e in scaffold.generate_manifest(ROOT)['files']}
        # Project orientation + the agent's workflow procedures ship into archives.
        self.assertIn('README.md', paths)
        self.assertIn('.claude/skills/README.md', paths)
        # but the spec-repo's own agent config does not.
        self.assertNotIn('.claude/settings.json', paths)

    def test_manifest_excludes_builder_docs(self):
        # The tool-BUILDING docs are not vendored into an archive: no tool reads
        # them at run time and a genealogist never needs them (workshop-only).
        paths = {e['path'] for e in scaffold.generate_manifest(ROOT)['files']}
        for builder in ('BUILD.md', 'BUILD_INGESTION.md', 'BUILD_INTERFACE.md',
                        'TOOLING_INGESTION.md', 'TOOLING_INTERFACE.md',
                        'AGENTS_TOOLING.md'):
            self.assertNotIn(builder, paths, builder)
        # The operating spec/agent docs that DO ship stay.
        for shipped in ('SPEC.md', 'TOOLING.md', 'AGENTS.md', 'CLAUDE.md', 'README.md'):
            self.assertIn(shipped, paths, shipped)

    def test_manifest_includes_launchers(self):
        # plan 17 + archive-layout: the double-clickable workbench launcher AND
        # the terminal CLI shims all ship into every archive - BOTH platforms'
        # shims regardless of the installing OS, because an archive is a portable
        # folder that may well be opened on a different machine than it was made
        # on. All are layout-agnostic - they probe .fha/tools/ first, then
        # tools/ - so one vendored file works flat or consolidated under .fha/.
        entries = {e['path']: e for e in scaffold.generate_manifest(ROOT)['files']}
        for launcher in ('serve.cmd', 'fha.cmd', 'fha'):
            self.assertIn(launcher, entries, launcher)
            self.assertEqual(entries[launcher]['category'], 'operating')
        serve = (ROOT / 'serve.cmd').read_text(encoding='utf-8')
        self.assertIn(r'.fha\tools\fha.py', serve)         # consolidated
        self.assertIn(r'tools\fha.py', serve)               # flat fallback
        fha_cmd = (ROOT / 'fha.cmd').read_text(encoding='utf-8')
        self.assertIn(r'.fha\tools\fha.py', fha_cmd)

    def test_double_click_launcher_never_shows_a_raw_error(self):
        # serve.cmd is the file a NON-TECHNICAL owner double-clicks, so it must
        # never flash a raw interpreter error and vanish. fha.cmd already guards
        # both failure modes; serve.cmd must too - by delegating to it, or (for an
        # archive predating the launchers) by checking the same two things itself.
        serve = (ROOT / 'serve.cmd').read_text(encoding='utf-8')
        self.assertIn('fha.cmd', serve, 'should hand over to the hardened shim')
        self.assertIn('version_info >= (3, 10)', serve,
                      'a standalone fallback must still check the Python version')
        self.assertIn(':no_tools', serve,
                      'a missing toolset must produce guidance, not a raw error')
        # Every exit path a double-click can reach has to hold the window open.
        for label in (':no_tools', ':no_python', ':trouble'):
            # Split on the label DEFINITION (start of line), not the goto above it.
            tail = serve.split(f'\n{label}\n', 1)[1].split('exit /b', 1)[0]
            self.assertIn('pause', tail,
                          f'{label} must pause so the message can be read')

    def test_posix_launcher_is_usable(self):
        # Without this file, every `fha ...` example in the guides is a
        # `command not found` on macOS and Linux - including the very first
        # post-install health check.
        posix = ROOT / 'fha'
        self.assertTrue(posix.is_file(), 'the POSIX `fha` launcher must ship')
        text = posix.read_text(encoding='utf-8')
        self.assertTrue(text.startswith('#!/bin/sh'), 'needs a shebang')
        self.assertIn('.fha/tools/fha.py', text)   # consolidated, probed first
        self.assertIn('tools/fha.py', text)        # flat fallback
        # LF-only: .gitattributes pins it so a Windows checkout cannot produce a
        # CRLF script that /bin/sh chokes on (and that would break its checksum).
        self.assertNotIn(b'\r\n', posix.read_bytes())
        if os.name != 'nt':
            self.assertTrue(os.access(posix, os.X_OK),
                            'the POSIX launcher must be executable')
        # The tool suite is 3.10+ syntax, so a python3 that is 3.8/3.9 must be
        # REJECTED rather than handed the code - otherwise the user gets a raw
        # SyntaxError instead of the launcher's install guidance. Both candidates
        # are probed for the real version, not trusted by name.
        self.assertEqual(text.count('version_info >= (3, 10)'), 1)
        self.assertIn('for candidate in python3 python', text)
        # The missing-tools message must name a command that can actually run:
        # `fha update-tools` alone loops back here, and update-tools needs both
        # --repo and --root when driven from outside the archive.
        recovery = text.split('cannot find the tools')[1]
        self.assertIn('--repo', recovery)
        self.assertIn('--root', recovery)

    @unittest.skipIf(os.name == 'nt', 'POSIX launcher; /bin/sh not available')
    def test_posix_launcher_rejects_old_python_and_guides(self):
        # Behavioural, not just textual: stand up a fake `python3` that reports
        # older than 3.10 and confirm the launcher refuses it with guidance.
        with tempfile.TemporaryDirectory() as td:
            box = Path(td)
            shutil.copy2(ROOT / 'fha', box / 'fha')
            os.chmod(box / 'fha', 0o755)
            _write(box / 'tools' / 'fha.py', 'print("SHOULD NOT RUN")\n')
            fakebin = box / 'bin'
            for name in ('python3', 'python'):
                _write(fakebin / name,
                       '#!/bin/sh\ncase "$*" in *version_info*) exit 1 ;; esac\n'
                       'echo SHOULD-NOT-RUN\n')
                os.chmod(fakebin / name, 0o755)
            # PATH holds ONLY the fake interpreters, so neither candidate can
            # satisfy the version probe and the guidance path must be taken.
            proc = subprocess.run(
                [str(box / 'fha'), 'lint'], capture_output=True, text=True,
                env={**os.environ, 'PATH': str(fakebin)})
            self.assertEqual(proc.returncode, EXIT_FAILURE)
            self.assertIn('3.10', proc.stderr)
            self.assertNotIn('SHOULD-NOT-RUN', proc.stdout)

    @unittest.skipIf(os.name == 'nt', 'POSIX launcher; /bin/sh not available')
    def test_posix_launcher_missing_tools_message_is_actionable(self):
        with tempfile.TemporaryDirectory() as td:
            box = Path(td)
            shutil.copy2(ROOT / 'fha', box / 'fha')
            os.chmod(box / 'fha', 0o755)
            proc = subprocess.run([str(box / 'fha'), 'lint'],
                                  capture_output=True, text=True)
            self.assertEqual(proc.returncode, EXIT_FAILURE)
            # Names the archive it could not repair, and a runnable command.
            self.assertIn(str(box), proc.stderr)
            self.assertIn('update-tools', proc.stderr)
            self.assertIn('--repo', proc.stderr)
            self.assertIn('--root', proc.stderr)

    def test_windows_launcher_validates_python(self):
        # A machine with no `py` launcher, or one whose `py -3` is older than
        # 3.10, otherwise gets a bare "not recognized" or a raw SyntaxError -
        # neither of which tells a non-technical owner what to do. The POSIX
        # launcher already guides them; Windows must match.
        text = (ROOT / 'fha.cmd').read_text(encoding='utf-8')
        self.assertEqual(text.count('sys.version_info >= (3, 10)'), 2)  # py, python
        self.assertIn('python.org/downloads', text)
        self.assertIn(':no_python', text)
        # cmd expands %VAR% when it PARSES a parenthesised block, so a variable
        # set and read in one block reads a stale value. The interpreter choice
        # must therefore not be made inside an if-block.
        self.assertNotIn('if not defined FHA_PY (', text)

    def test_windows_launcher_handles_missing_tools(self):
        # Parity with the POSIX launcher: without this, a damaged archive hands
        # the missing path straight to Python and the Windows user gets a raw
        # interpreter error with no recovery step.
        text = (ROOT / 'fha.cmd').read_text(encoding='utf-8')
        self.assertIn(r'if exist "%~dp0tools\fha.py"', text)
        self.assertIn('cannot find the tools', text)
        recovery = text.split('cannot find the tools')[1]
        self.assertIn('update-tools', recovery)
        self.assertIn('--repo', recovery)
        self.assertIn('--root', recovery)
        self.assertIn('exit /b 3', text)

    def test_shipped_rulebooks_do_not_link_relatively_to_unshipped_docs(self):
        # AGENTS.md/CLAUDE.md tell an agent to read AGENTS_TOOLING.md, which this
        # PR stopped vendoring. In an installed archive a relative link there is a
        # dead end, so the mandated checklist cannot be followed. Every reference
        # from a SHIPPED file to an UNSHIPPED doc must be an absolute URL.
        shipped = {e['path'] for e in scaffold.generate_manifest(ROOT)['files']}
        unshipped = ('AGENTS_TOOLING.md', 'BUILD.md', 'BUILD_INGESTION.md',
                     'BUILD_INTERFACE.md', 'TOOLING_INGESTION.md',
                     'TOOLING_INTERFACE.md')
        for doc in unshipped:
            self.assertNotIn(doc, shipped, f'{doc} is workshop-only')
        offenders = []
        for rel in sorted(shipped):
            src = ROOT / rel
            if src.suffix != '.md' or not src.is_file():
                continue
            text = src.read_text(encoding='utf-8', errors='replace')
            for doc in unshipped:
                for form in (f']({doc})', f'](../{doc})', f'](../../{doc})'):
                    if form in text:
                        offenders.append(f'{rel} -> {form}')
        self.assertEqual(offenders, [], f'relative links to workshop-only docs: {offenders}')

    def test_skeleton_and_operating_categories(self):
        files = scaffold.generate_manifest(ROOT)['files']
        by_path = {e['path']: e for e in files}
        # Skeleton seeds present, remapped, and carry a src that differs.
        self.assertEqual(by_path['fha.yaml']['category'], 'skeleton')
        self.assertEqual(by_path['fha.yaml']['src'], 'archive-template/fha.yaml')
        self.assertEqual(by_path['places/places.yaml']['category'], 'skeleton')
        # The five BUILD-mandated docs ship, at the archive ROOT: only the
        # machinery (tools/, design/) is vendored under .fha/. docs/ stays put so
        # its two-way link graph with the rulebooks keeps resolving - see
        # test_docs_stay_at_archive_root.
        for doc in ('docs/GETTING_STARTED.md', 'docs/SETUP_FROM_ZIP.md',
                    'docs/CHEATSHEET.md', 'docs/TROUBLESHOOTING.md',
                    'docs/FILING_CABINET.md'):
            self.assertIn(doc, by_path, doc)
            self.assertEqual(by_path[doc]['category'], 'operating')
        # A vendored operating entry carries a src remap (repo-flat -> archive
        # .fha/); a root-pinned operating entry (SPEC.md) carries none.
        self.assertEqual(by_path['.fha/tools/scaffold.py']['src'], 'tools/scaffold.py')
        self.assertNotIn('src', by_path['SPEC.md'])

    def test_owner_docs_stay_at_root_and_project_docs_are_vendored(self):
        # Owner-facing docs are the manual someone reaches for when something is
        # wrong - exactly when a hidden folder helps least - and they sit in a
        # two-way link graph with the root rulebooks (README.md ->
        # `docs/GETTING_STARTED.md`; docs -> `../SPEC.md`), which only survives if
        # both ends stay put. Project docs (the visual-language reference, the
        # roadmap) are not owner material and ride with the machinery instead.
        by_path = {e['path']: e for e in scaffold.generate_manifest(ROOT)['files']}
        doc_paths = [p for p in by_path if p.split('/')[0] == 'docs']
        self.assertTrue(doc_paths, 'docs/ must ship')
        for p in doc_paths:
            self.assertNotIn('src', by_path[p], f'{p} must not be remapped')
        # Exactly the declared project docs are vendored - nothing else drifts in.
        self.assertEqual(
            sorted(p for p in by_path if p.startswith('.fha/docs/')),
            sorted(f'.fha/{d}' for d in scaffold._VENDORED_DOCS),
            'only the declared project docs may live under .fha/docs/')
        # A vendored doc must not also ship at the root, or an archive holds two
        # copies and the owner edits whichever they find first.
        for d in scaffold._VENDORED_DOCS:
            self.assertNotIn(d, by_path, f'{d} must not also install at the root')
        # Both ends of the link graph land where the links expect them.
        self.assertIn('README.md', by_path)
        self.assertIn('docs/GETTING_STARTED.md', by_path)
        # Meanwhile the machinery IS vendored.
        self.assertTrue([p for p in by_path if p.startswith('.fha/tools/')])
        self.assertTrue([p for p in by_path if p.startswith('.fha/design/')])


class InstallTest(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self.repo = _make_fake_repo(self.tmp / 'repo')
        self.archive = self.tmp / 'archive'

    def tearDown(self):
        self._tmp.cleanup()

    def test_install_copies_files_and_stamps(self):
        rc = scaffold.run_install(self.archive, self.repo)
        self.assertEqual(rc, EXIT_CLEAN)
        # operating + skeleton landed, remapped correctly
        self.assertTrue((self.archive / 'SPEC.md').is_file())
        self.assertTrue((self.archive / '.fha' / 'tools' /'atool.py').is_file())
        self.assertTrue((self.archive / 'docs' / 'guide.md').is_file())
        self.assertTrue((self.archive / 'fha.yaml').is_file())
        self.assertTrue((self.archive / 'places' / 'places.yaml').is_file())
        self.assertTrue((self.archive / 'sources' / '.gitkeep').is_file())
        # archive-template/ folder itself is never created in the archive
        self.assertFalse((self.archive / 'archive-template').exists())
        # stamp records every copied file's checksum
        stamp = json.loads((self.archive / '.plaintext-version').read_text(encoding='utf-8'))
        self.assertIn('SPEC.md', stamp['files'])
        self.assertIn('fha.yaml', stamp['files'])
        self.assertEqual(stamp['manifest_version'], scaffold.MANIFEST_VERSION)

    def test_install_dry_run_writes_nothing(self):
        rc = scaffold.run_install(self.archive, self.repo, dry_run=True)
        self.assertEqual(rc, EXIT_CLEAN)
        self.assertFalse(self.archive.exists())

    def test_reinstall_refused(self):
        scaffold.run_install(self.archive, self.repo)
        with self.assertRaises(scaffold.ScaffoldError) as ctx:
            scaffold.run_install(self.archive, self.repo)
        self.assertIn('already', str(ctx.exception).lower())

    def test_missing_source_refused_before_writing(self):
        (self.repo / 'tools' / 'atool.py').unlink()  # manifest still lists it
        with self.assertRaises(scaffold.ScaffoldError) as ctx:
            scaffold.run_install(self.archive, self.repo)
        self.assertIn('missing', str(ctx.exception).lower())
        # nothing half-written
        self.assertFalse(self.archive.exists())

    def test_missing_manifest_is_friendly(self):
        (self.repo / 'manifest.json').unlink()
        with self.assertRaises(scaffold.ScaffoldError) as ctx:
            scaffold.run_install(self.archive, self.repo)
        self.assertIn('manifest.json', str(ctx.exception))

    def test_python_too_old_is_a_hard_stop(self):
        with mock.patch.object(scaffold.sys, 'version_info', (3, 9, 0)):
            rc = scaffold._cmd_install(argparse.Namespace(
                archive_path=str(self.archive), repo=str(self.repo), dry_run=False))
        self.assertEqual(rc, EXIT_FAILURE)
        self.assertFalse(self.archive.exists())

    def test_exiftool_missing_is_only_advisory(self):
        with mock.patch('scaffold.shutil.which', return_value=None):
            rc = scaffold.run_install(self.archive, self.repo)
        self.assertEqual(rc, EXIT_CLEAN)  # install still succeeds
        self.assertTrue((self.archive / 'SPEC.md').is_file())


class PipCommandTest(unittest.TestCase):
    """The recovery command must run as printed, for the interpreter it names."""

    def test_a_spaced_interpreter_path_is_quoted(self):
        import _lib
        with mock.patch.object(_lib.sys, 'executable', '/home/u/Family Tools/python'):
            cmd = _lib.pip_command('pyyaml')
        # Pasteable: the shell must see one argument, not two.
        self.assertEqual(shlex.split(cmd)[0], '/home/u/Family Tools/python')
        self.assertEqual(shlex.split(cmd)[1:], ['-m', 'pip', 'install', 'pyyaml'])

    def test_it_names_the_running_interpreter(self):
        import _lib
        self.assertTrue(_lib.pip_command('pyyaml').startswith(
            shlex.quote(_lib.sys.executable)))


class InstallTemplateHandCopyTest(unittest.TestCase):
    """The documented zip on-ramp: copy archive-template/, then run install.

    SETUP_FROM_ZIP.md tells people to do exactly this, and README.md is an
    operating file whose template copy differs from the installed one BY DESIGN.
    So install's preflight has to accept the template bytes at a destination it
    would otherwise refuse - the permissive half of `_acceptable`. Without a test
    here, dropping the template sha from that set passes the whole suite while
    silently blocking every hand-copy user.
    """

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self.repo = _make_fake_repo(self.tmp / 'repo')
        # An operating file whose archive-template counterpart DIFFERS, which is
        # the real README.md situation the branch exists for.
        _write(self.repo / 'README.md', '# stock readme\n')
        _write(self.repo / 'archive-template' / 'README.md',
               '# template readme - different by design\n')
        scaffold._write_manifest(self.repo)

    def tearDown(self):
        self._tmp.cleanup()

    def test_install_accepts_a_pristine_hand_copied_template(self):
        archive = self.tmp / 'archive'
        archive.mkdir()
        # What the guide tells the user to do: copy the template across first.
        _write(archive / 'README.md',
               (self.repo / 'archive-template' / 'README.md').read_text(encoding='utf-8'))
        _write(archive / 'fha.yaml',
               (self.repo / 'archive-template' / 'fha.yaml').read_text(encoding='utf-8'))

        with contextlib.redirect_stdout(io.StringIO()):
            rc = scaffold.run_install(archive, self.repo)

        self.assertEqual(rc.exit_code, EXIT_CLEAN)
        # And the template copy is upgraded to stock, not left behind.
        self.assertEqual((archive / 'README.md').read_text(encoding='utf-8'),
                         '# stock readme\n')

    def test_install_still_refuses_an_edited_operating_file(self):
        # The refusal side must survive the permissive branch: bytes that are
        # neither stock nor the template are the owner's own work.
        archive = self.tmp / 'archive'
        archive.mkdir()
        _write(archive / 'README.md', '# my own notes, do not clobber\n')
        with self.assertRaises(scaffold.ScaffoldError) as caught:
            scaffold.run_install(archive, self.repo)
        self.assertIn('README.md', str(caught.exception))


class UpdateToolsTest(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self.repo = _make_fake_repo(self.tmp / 'repo')
        self.archive = self.tmp / 'archive'
        scaffold.run_install(self.archive, self.repo)

    def tearDown(self):
        self._tmp.cleanup()

    def _stamp(self):
        return json.loads((self.archive / '.plaintext-version').read_text(encoding='utf-8'))

    def test_malformed_stamp_files_value_does_not_traceback(self):
        # A hand-mangled stamp whose `files` is valid JSON but not an object used
        # to raise AttributeError from .items() mid-run.
        stamp = self._stamp()
        stamp['files'] = 'not-an-object'
        _write(self.archive / '.plaintext-version', json.dumps(stamp))
        with contextlib.redirect_stdout(io.StringIO()):
            rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertIn(rc.exit_code, (EXIT_CLEAN, EXIT_WARNINGS))
        self.assertIsInstance(self._stamp()['files'], dict)

    def test_manifest_entry_with_a_null_field_refuses_plainly(self):
        # `path` alone is not the whole contract: repo_root / None is a
        # TypeError traceback mid-preflight rather than a refusal. An explicit
        # null is the case that matters - .get(k, fallback) returns None when the
        # key is THERE holding a null, so "absent" and "null" are not the same.
        pristine = (self.repo / 'manifest.json').read_text(encoding='utf-8')
        for field in ('src', 'category', 'sha256'):
            with self.subTest(field=field):
                _write(self.repo / 'manifest.json', pristine)
                manifest = json.loads(pristine)
                manifest['files'][0][field] = None
                _write(self.repo / 'manifest.json', json.dumps(manifest))
                with self.assertRaises(scaffold.ScaffoldError) as caught:
                    scaffold.load_manifest(self.repo)
                self.assertIn(field, str(caught.exception))

    def test_noop_when_current(self):
        rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc, EXIT_CLEAN)
        self.assertFalse((self.archive / '.plaintext-backup').exists())

    def test_stock_change_overwrites_silently(self):
        # Upstream improved atool.py; the archive's copy is still pristine.
        _write(self.repo / 'tools' / 'atool.py', 'print("a tool v2")\n')
        scaffold._write_manifest(self.repo)
        rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc, EXIT_CLEAN)
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("a tool v2")\n')
        self.assertFalse((self.archive / '.plaintext-backup').exists())
        # stamp now records the new checksum
        self.assertEqual(self._stamp()['files']['.fha/tools/atool.py'],
                         scaffold._sha256_file(self.repo / 'tools' / 'atool.py'))

    def test_customized_file_is_backed_up_then_updated(self):
        # Archive owner edited their atool.py; upstream also moved on.
        _write(self.archive / '.fha' / 'tools' /'atool.py', 'print("MY EDIT")\n')
        _write(self.repo / 'tools' / 'atool.py', 'print("a tool v2")\n')
        scaffold._write_manifest(self.repo)
        rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc, EXIT_CLEAN)
        # live file is the new stock
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("a tool v2")\n')
        # the edit survives in the backup
        backups = list((self.archive / '.plaintext-backup').rglob('atool.py'))
        self.assertEqual(len(backups), 1)
        self.assertEqual(backups[0].read_text(encoding='utf-8'), 'print("MY EDIT")\n')

    def test_skeleton_files_are_never_touched(self):
        # The critical safety property: a user's fha.yaml/places.yaml is data, not
        # operating layer - update-tools must leave it exactly as-is, even if
        # upstream's template changed.
        _write(self.archive / 'fha.yaml', 'roots:\n  photos: D:/MyPhotos\n')
        _write(self.archive / 'places' / 'places.yaml', '- id: L-abc\n  name: MyTown\n')
        _write(self.repo / 'archive-template' / 'fha.yaml', 'roots:\n  photos: changed\n')
        scaffold._write_manifest(self.repo)
        scaffold.run_update_tools(self.archive, self.repo)
        self.assertIn('MyPhotos', (self.archive / 'fha.yaml').read_text(encoding='utf-8'))
        self.assertIn('MyTown', (self.archive / 'places' / 'places.yaml').read_text(encoding='utf-8'))
        # never even backed up
        self.assertFalse((self.archive / '.plaintext-backup').exists())

    def test_retired_file_moved_to_backup(self):
        # Inject a recorded tool that the manifest no longer lists.
        retired = self.archive / '.fha' / 'tools' /'oldtool.py'
        _write(retired, 'print("old")\n')
        stamp = self._stamp()
        stamp['files']['.fha/tools/oldtool.py'] = 'deadbeef'
        _write(self.archive / '.plaintext-version', json.dumps(stamp))
        rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc, EXIT_CLEAN)
        self.assertFalse(retired.exists())
        moved = list((self.archive / '.plaintext-backup').rglob('oldtool.py'))
        self.assertEqual(len(moved), 1)
        # and it's dropped from the refreshed stamp
        self.assertNotIn('.fha/tools/oldtool.py', self._stamp()['files'])

    def test_added_file_copied_in(self):
        _write(self.repo / 'tools' / 'newtool.py', 'print("new")\n')
        scaffold._write_manifest(self.repo)
        scaffold.run_update_tools(self.archive, self.repo)
        self.assertTrue((self.archive / '.fha' / 'tools' /'newtool.py').is_file())
        self.assertIn('.fha/tools/newtool.py', self._stamp()['files'])

    def test_dry_run_writes_nothing(self):
        _write(self.archive / '.fha' / 'tools' /'atool.py', 'print("MY EDIT")\n')
        _write(self.repo / 'tools' / 'atool.py', 'print("v2")\n')
        scaffold._write_manifest(self.repo)
        rc = scaffold.run_update_tools(self.archive, self.repo, dry_run=True)
        self.assertEqual(rc, EXIT_CLEAN)
        # the customized file is left exactly as the user had it; no backup made
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("MY EDIT")\n')
        self.assertFalse((self.archive / '.plaintext-backup').exists())

    def test_broken_clone_refused_before_any_mutation(self):
        # A file the manifest lists but the clone no longer ships must abort the
        # update before anything is copied or backed up.
        _write(self.archive / '.fha' / 'tools' /'atool.py', 'print("MY EDIT")\n')  # would be customized
        _write(self.repo / 'tools' / 'newtool.py', 'print("new")\n')
        scaffold._write_manifest(self.repo)            # manifest now lists newtool.py
        (self.repo / 'tools' / 'newtool.py').unlink()  # ...then the source vanishes
        with self.assertRaises(scaffold.ScaffoldError) as ctx:
            scaffold.run_update_tools(self.archive, self.repo)
        self.assertIn('missing', str(ctx.exception).lower())
        # the customized file was NOT moved to backup
        self.assertFalse((self.archive / '.plaintext-backup').exists())
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("MY EDIT")\n')

    def test_partial_failure_does_not_claim_success(self):
        # A per-file failure must not produce a success message or inflate the
        # summary counts (the output stays honest), and must surface the failure.
        _write(self.archive / '.fha' / 'tools' /'atool.py', 'print("MY EDIT")\n')  # customized
        _write(self.repo / 'tools' / 'atool.py', 'print("v2")\n')
        scaffold._write_manifest(self.repo)
        out, err = io.StringIO(), io.StringIO()
        with mock.patch('scaffold.shutil.move', side_effect=OSError('locked')):
            with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
                rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc, EXIT_WARNINGS)
        self.assertNotIn('has been backed up', out.getvalue())          # no false success
        self.assertIn('Done: 0 added, 0 updated, 0 backed up', out.getvalue())  # honest counts
        self.assertIn('could not be updated', err.getvalue())           # failure surfaced
        # the edit is intact (the move failed before touching it); nothing backed up
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("MY EDIT")\n')
        self.assertEqual(list((self.archive / '.plaintext-backup').rglob('atool.py')), [])

    def test_failed_update_keeps_edit_safe_on_retry(self):
        # Regression: a failed customized-file update must NOT record the edited
        # bytes as the installed baseline. If it did, the retry would see
        # disk == recorded, classify the file as pristine stock, and silently
        # overwrite the human's edit with no backup (data loss).
        _write(self.archive / '.fha' / 'tools' /'atool.py', 'print("MY EDIT")\n')
        _write(self.repo / 'tools' / 'atool.py', 'print("v2")\n')
        scaffold._write_manifest(self.repo)
        # Run 1: move fails.
        with mock.patch('scaffold.shutil.move', side_effect=OSError('locked')):
            with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
                self.assertEqual(scaffold.run_update_tools(self.archive, self.repo), EXIT_WARNINGS)
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("MY EDIT")\n')
        # Run 2: move works. The edit must be BACKED UP, not silently overwritten.
        with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
            self.assertEqual(scaffold.run_update_tools(self.archive, self.repo), EXIT_CLEAN)
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("v2")\n')
        backups = list((self.archive / '.plaintext-backup').rglob('atool.py'))
        self.assertEqual(len(backups), 1)
        self.assertEqual(backups[0].read_text(encoding='utf-8'), 'print("MY EDIT")\n')

    def test_failed_retired_move_is_retried_next_run(self):
        # A retired file whose move fails must stay recorded so the next run
        # re-detects and retries it (a successful move drops it from the stamp).
        retired = self.archive / '.fha' / 'tools' /'oldtool.py'
        _write(retired, 'print("old")\n')
        stamp = json.loads((self.archive / '.plaintext-version').read_text(encoding='utf-8'))
        stamp['files']['.fha/tools/oldtool.py'] = 'deadbeef'
        _write(self.archive / '.plaintext-version', json.dumps(stamp))
        with mock.patch('scaffold.shutil.move', side_effect=OSError('locked')):
            with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
                self.assertEqual(scaffold.run_update_tools(self.archive, self.repo), EXIT_WARNINGS)
        self.assertTrue(retired.exists())  # move failed, file still there
        # still recorded → still detectable as retired
        new_stamp = json.loads((self.archive / '.plaintext-version').read_text(encoding='utf-8'))
        self.assertIn('.fha/tools/oldtool.py', new_stamp['files'])
        # retry succeeds and moves it to backup
        with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
            self.assertEqual(scaffold.run_update_tools(self.archive, self.repo), EXIT_CLEAN)
        self.assertFalse(retired.exists())
        self.assertEqual(len(list((self.archive / '.plaintext-backup').rglob('oldtool.py'))), 1)

    def test_no_version_stamp_treats_existing_as_customized(self):
        # An archive whose tools were hand-copied (no install) still must not lose
        # a hand-edit on update.
        (self.archive / '.plaintext-version').unlink()
        _write(self.archive / '.fha' / 'tools' /'atool.py', 'print("HAND EDIT")\n')
        scaffold.run_update_tools(self.archive, self.repo)
        backups = list((self.archive / '.plaintext-backup').rglob('atool.py'))
        self.assertEqual(len(backups), 1)
        self.assertEqual(backups[0].read_text(encoding='utf-8'), 'print("HAND EDIT")\n')


class CmdErrorPathTest(unittest.TestCase):
    """The argparse bridges return friendly exit codes, never tracebacks."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self.repo = _make_fake_repo(self.tmp / 'repo')

    def tearDown(self):
        self._tmp.cleanup()

    def test_update_missing_repo(self):
        rc = scaffold._cmd_update_tools(argparse.Namespace(
            repo=None, root=str(self.tmp), dry_run=False, verbose=False))
        self.assertEqual(rc, EXIT_FAILURE)

    def test_update_not_an_archive(self):
        # root points at a folder with no fha.yaml; no auto-detect either.
        empty = self.tmp / 'not-an-archive'
        empty.mkdir()
        # find_archive_root walks up from CWD; force the no-root branch by passing
        # a root that exists but isn't an archive - _cmd uses the explicit root, so
        # update runs and fails to find a manifest? No: it runs against that root.
        # Instead drop --root and patch find_archive_root to None.
        with mock.patch('scaffold.find_archive_root', return_value=None):
            rc = scaffold._cmd_update_tools(argparse.Namespace(
                repo=str(self.repo), root=None, dry_run=False, verbose=False))
        self.assertEqual(rc, EXIT_FAILURE)

    def test_update_explicit_root_must_be_an_archive(self):
        # A mistyped --root (a real folder, but not an archive) must be refused
        # before any operating-layer file is written into it.
        not_arch = self.tmp / 'not-an-archive'
        not_arch.mkdir()
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            rc = scaffold._cmd_update_tools(argparse.Namespace(
                repo=str(self.repo), root=str(not_arch), dry_run=False, verbose=False))
        self.assertEqual(rc, EXIT_FAILURE)
        self.assertIn('does not look like an archive', err.getvalue())
        self.assertEqual(list(not_arch.iterdir()), [])  # nothing written

    def test_install_bad_repo_is_friendly_exit(self):
        rc = scaffold._cmd_install(argparse.Namespace(
            archive_path=str(self.tmp / 'arch'),
            repo=str(self.tmp / 'no-such-repo'), dry_run=False))
        self.assertEqual(rc, EXIT_FAILURE)


def _make_flat_archive(root: Path, *, with_stamp: bool = True) -> Path:
    """A pre-.fha archive: tools/, docs/, design/ at the root + a flat stamp.

    Note `serve.cmd`: a real pre-.fha archive's launcher names `tools\\fha.py`
    directly and knows nothing about a vendor folder, and `fha`/`fha.cmd` may not
    exist at all - which is exactly what moving tools/ breaks.
    """
    _write(root / 'fha.yaml', 'roots:\n  photos: photos\n  documents: documents\n')
    _write(root / 'SPEC.md', '# SPEC\n')          # root rulebook, stays put
    _write(root / 'CLAUDE.md', '# CLAUDE\n')      # root rulebook, stays put
    _write(root / 'serve.cmd', '@echo off\npy -3 tools\\fha.py serve %*\n')  # stale
    _write(root / 'tools' / 'fha.py', 'print("fha")\n')
    _write(root / 'tools' / 'sub' / 'x.py', 'x = 1\n')
    _write(root / 'docs' / 'guide.md', '# guide\n')        # stays at the root
    _write(root / 'design' / 'styles.css', 'body{}\n')      # vendored (in stamp)
    _write(root / 'design' / 'custom.css', '/* mine */\n')  # skeleton (NOT in stamp)
    _write(root / '.claude' / 'skills' / 's.md', '# skill\n')  # stays at root
    _write(root / 'people' / '.gitkeep', '')                # a record, untouched
    if with_stamp:
        stamp = {
            'manifest_version': '1', 'spec_version': '1.2',
            'installed': '2026-01-01T00:00:00',
            'files': {
                'tools/fha.py': 'aaa', 'tools/sub/x.py': 'bbb',
                'docs/guide.md': 'ccc', 'design/styles.css': 'ddd',
                'SPEC.md': 'eee', '.claude/skills/s.md': 'fff',
            },
        }
        _write(root / '.plaintext-version', json.dumps(stamp))
    return root


def _make_launcher_repo(root: Path) -> Path:
    """A stand-in workshop holding just the current root launchers."""
    _write(root / 'serve.cmd', '@echo off\nif exist ".fha\\tools\\fha.py" (echo new)\n')
    _write(root / 'fha.cmd', '@echo off\nrem .fha probe\n')
    _write(root / 'fha', '#!/bin/sh\n# .fha probe\n')
    return root


if __name__ == '__main__':
    unittest.main()
