"""
Tests for tools/scaffold.py - `fha install` and `fha update-tools` (BUILD.md M9).

Two layers:
  1. A manifest-sync guard that recomputes the operating-layer manifest from the
     real repo and asserts the committed manifest.json still matches it - so a PR
     that changes a tool/doc/skeleton file but forgets to regenerate fails here.
  2. Behavior tests against a small, hand-built FAKE repo (no .git/, proving the
     git-free / zip install path) and throwaway archives, exercising install,
     re-install refusal, the four update outcomes (add/stock/customized/retired),
     the critical skeleton-is-never-touched safety property, dry-run no-ops, and
     the friendly error paths.

Run: python -m unittest tests.test_scaffold -v
"""

import argparse
import contextlib
import io
import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'tools'))

import scaffold
from _lib import EXIT_CLEAN, EXIT_FAILURE, EXIT_WARNINGS


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='utf-8')


def _make_fake_repo(repo: Path) -> Path:
    """Build a minimal public-repo clone: 3 operating files + 3 skeleton seeds.

    Deliberately tiny so the tests are fast and every file's role is obvious. No
    .git/ is created anywhere - install/update working against this directory is
    itself the proof of the zip-based, git-free path (BUILD.md M9.1).
    """
    _write(repo / 'SPEC.md', '# SPEC\n\n**Version 9.9 - 2026-01-01**\n\nbody\n')
    _write(repo / 'tools' / 'atool.py', 'print("a tool")\n')
    _write(repo / 'docs' / 'guide.md', '# Guide\n')
    # bytecode that must NOT enter the manifest
    _write(repo / 'tools' / '__pycache__' / 'atool.cpython-312.pyc', 'junk\n')
    # skeleton (remapped from archive-template/ → archive root)
    _write(repo / 'archive-template' / 'fha.yaml', 'roots:\n  photos: photos\n')
    _write(repo / 'archive-template' / 'places' / 'places.yaml', '# places\n')
    _write(repo / 'archive-template' / 'sources' / '.gitkeep', '')
    _write(repo / 'archive-template' / 'README.md', 'template readme - excluded\n')
    # The install-once skeleton override that lives UNDER an operating subtree,
    # so it is the one seed whose archive path moves with the vendor layout.
    _write(repo / 'design' / 'custom.css', '/* stock */\n')
    scaffold._write_manifest(repo)
    return repo


class ManifestSyncTest(unittest.TestCase):
    """The committed manifest.json must match what the repo currently contains."""

    @unittest.skipIf(sys.platform == 'win32',
                     'git core.autocrlf rewrites tracked LF files (e.g. '
                     'design/custom.css, serve.cmd) to CRLF on a Windows '
                     'checkout, so regenerated byte-hashes differ from the '
                     'LF-based committed manifest; CI (Linux) checks currency.')
    def test_committed_manifest_is_current(self):
        committed = json.loads((ROOT / 'manifest.json').read_text(encoding='utf-8'))
        regenerated = scaffold.generate_manifest(ROOT)
        # `generated` is a date stamp that legitimately changes day to day; the
        # contract is the file set + checksums + versions.
        self.assertEqual(committed['manifest_version'], regenerated['manifest_version'])
        self.assertEqual(committed['spec_version'], regenerated['spec_version'])
        self.assertEqual(
            committed['files'], regenerated['files'],
            'manifest.json is out of date - run '
            '`python tools/scaffold.py write-manifest --repo .` and commit the result.',
        )

    def test_manifest_excludes_repo_furniture(self):
        paths = {e['path'] for e in scaffold.generate_manifest(ROOT)['files']}
        # Public-repo furniture that must never enter an archive: PRIVACY.md is the
        # "no real data" policy (contradictory inside a real archive), and the
        # release checklist / packing list / template's own readme are spec-repo
        # maintenance.
        for furniture in ('PRIVACY.md', 'RELEASE_CHECKLIST.md',
                          'manifest.json', 'archive-template/README.md'):
            self.assertNotIn(furniture, paths)
        # No bytecode, no example/test furniture.
        self.assertFalse(any('__pycache__' in p or p.endswith('.pyc') for p in paths))
        self.assertFalse(any(p.startswith(('example-archive/', 'tests/', 'archive-template/'))
                             for p in paths))

    def test_manifest_includes_operating_extras(self):
        paths = {e['path'] for e in scaffold.generate_manifest(ROOT)['files']}
        # Project orientation + the agent's workflow procedures ship into archives.
        self.assertIn('README.md', paths)
        self.assertIn('.claude/skills/README.md', paths)
        # but the spec-repo's own agent config does not.
        self.assertNotIn('.claude/settings.json', paths)

    def test_manifest_excludes_builder_docs(self):
        # The tool-BUILDING docs are not vendored into an archive: no tool reads
        # them at run time and a genealogist never needs them (workshop-only).
        paths = {e['path'] for e in scaffold.generate_manifest(ROOT)['files']}
        for builder in ('BUILD.md', 'BUILD_INGESTION.md', 'BUILD_INTERFACE.md',
                        'TOOLING_INGESTION.md', 'TOOLING_INTERFACE.md',
                        'AGENTS_TOOLING.md'):
            self.assertNotIn(builder, paths, builder)
        # The operating spec/agent docs that DO ship stay.
        for shipped in ('SPEC.md', 'TOOLING.md', 'AGENTS.md', 'CLAUDE.md', 'README.md'):
            self.assertIn(shipped, paths, shipped)

    def test_manifest_includes_launchers(self):
        # plan 17 + archive-layout: the double-clickable workbench launcher AND
        # the terminal CLI shims all ship into every archive - BOTH platforms'
        # shims regardless of the installing OS, because an archive is a portable
        # folder that may well be opened on a different machine than it was made
        # on. All are layout-agnostic - they probe .fha/tools/ first, then
        # tools/ - so one vendored file works flat or consolidated under .fha/.
        entries = {e['path']: e for e in scaffold.generate_manifest(ROOT)['files']}
        for launcher in ('serve.cmd', 'fha.cmd', 'fha'):
            self.assertIn(launcher, entries, launcher)
            self.assertEqual(entries[launcher]['category'], 'operating')
        serve = (ROOT / 'serve.cmd').read_text(encoding='utf-8')
        self.assertIn(r'tools\fha.py serve', serve)        # flat fallback
        self.assertIn(r'.fha\tools\fha.py serve', serve)   # consolidated
        fha_cmd = (ROOT / 'fha.cmd').read_text(encoding='utf-8')
        self.assertIn(r'.fha\tools\fha.py', fha_cmd)

    def test_posix_launcher_is_usable(self):
        # Without this file, every `fha ...` example in the guides is a
        # `command not found` on macOS and Linux - including the very first
        # post-install health check.
        posix = ROOT / 'fha'
        self.assertTrue(posix.is_file(), 'the POSIX `fha` launcher must ship')
        text = posix.read_text(encoding='utf-8')
        self.assertTrue(text.startswith('#!/bin/sh'), 'needs a shebang')
        self.assertIn('.fha/tools/fha.py', text)   # consolidated, probed first
        self.assertIn('tools/fha.py', text)        # flat fallback
        # LF-only: .gitattributes pins it so a Windows checkout cannot produce a
        # CRLF script that /bin/sh chokes on (and that would break its checksum).
        self.assertNotIn(b'\r\n', posix.read_bytes())
        if os.name != 'nt':
            self.assertTrue(os.access(posix, os.X_OK),
                            'the POSIX launcher must be executable')
        # The tool suite is 3.10+ syntax, so a python3 that is 3.8/3.9 must be
        # REJECTED rather than handed the code - otherwise the user gets a raw
        # SyntaxError instead of the launcher's install guidance. Both candidates
        # are probed for the real version, not trusted by name.
        self.assertEqual(text.count('version_info >= (3, 10)'), 1)
        self.assertIn('for candidate in python3 python', text)
        # The missing-tools message must name a command that can actually run:
        # `fha update-tools` alone loops back here, and update-tools needs both
        # --repo and --root when driven from outside the archive.
        recovery = text.split('cannot find the tools')[1]
        self.assertIn('--repo', recovery)
        self.assertIn('--root', recovery)

    @unittest.skipIf(os.name == 'nt', 'POSIX launcher; /bin/sh not available')
    def test_posix_launcher_rejects_old_python_and_guides(self):
        # Behavioural, not just textual: stand up a fake `python3` that reports
        # older than 3.10 and confirm the launcher refuses it with guidance.
        with tempfile.TemporaryDirectory() as td:
            box = Path(td)
            shutil.copy2(ROOT / 'fha', box / 'fha')
            os.chmod(box / 'fha', 0o755)
            _write(box / 'tools' / 'fha.py', 'print("SHOULD NOT RUN")\n')
            fakebin = box / 'bin'
            for name in ('python3', 'python'):
                _write(fakebin / name,
                       '#!/bin/sh\ncase "$*" in *version_info*) exit 1 ;; esac\n'
                       'echo SHOULD-NOT-RUN\n')
                os.chmod(fakebin / name, 0o755)
            # PATH holds ONLY the fake interpreters, so neither candidate can
            # satisfy the version probe and the guidance path must be taken.
            proc = subprocess.run(
                [str(box / 'fha'), 'lint'], capture_output=True, text=True,
                env={**os.environ, 'PATH': str(fakebin)})
            self.assertEqual(proc.returncode, EXIT_FAILURE)
            self.assertIn('3.10', proc.stderr)
            self.assertNotIn('SHOULD-NOT-RUN', proc.stdout)

    @unittest.skipIf(os.name == 'nt', 'POSIX launcher; /bin/sh not available')
    def test_posix_launcher_missing_tools_message_is_actionable(self):
        with tempfile.TemporaryDirectory() as td:
            box = Path(td)
            shutil.copy2(ROOT / 'fha', box / 'fha')
            os.chmod(box / 'fha', 0o755)
            proc = subprocess.run([str(box / 'fha'), 'lint'],
                                  capture_output=True, text=True)
            self.assertEqual(proc.returncode, EXIT_FAILURE)
            # Names the archive it could not repair, and a runnable command.
            self.assertIn(str(box), proc.stderr)
            self.assertIn('update-tools', proc.stderr)
            self.assertIn('--repo', proc.stderr)
            self.assertIn('--root', proc.stderr)

    def test_windows_launcher_validates_python(self):
        # A machine with no `py` launcher, or one whose `py -3` is older than
        # 3.10, otherwise gets a bare "not recognized" or a raw SyntaxError -
        # neither of which tells a non-technical owner what to do. The POSIX
        # launcher already guides them; Windows must match.
        text = (ROOT / 'fha.cmd').read_text(encoding='utf-8')
        self.assertEqual(text.count('sys.version_info >= (3, 10)'), 2)  # py, python
        self.assertIn('python.org/downloads', text)
        self.assertIn(':no_python', text)
        # cmd expands %VAR% when it PARSES a parenthesised block, so a variable
        # set and read in one block reads a stale value. The interpreter choice
        # must therefore not be made inside an if-block.
        self.assertNotIn('if not defined FHA_PY (', text)

    def test_windows_launcher_handles_missing_tools(self):
        # Parity with the POSIX launcher: without this, a damaged archive hands
        # the missing path straight to Python and the Windows user gets a raw
        # interpreter error with no recovery step.
        text = (ROOT / 'fha.cmd').read_text(encoding='utf-8')
        self.assertIn(r'if exist "%~dp0tools\fha.py"', text)
        self.assertIn('cannot find the tools', text)
        recovery = text.split('cannot find the tools')[1]
        self.assertIn('update-tools', recovery)
        self.assertIn('--repo', recovery)
        self.assertIn('--root', recovery)
        self.assertIn('exit /b 3', text)

    def test_shipped_rulebooks_do_not_link_relatively_to_unshipped_docs(self):
        # AGENTS.md/CLAUDE.md tell an agent to read AGENTS_TOOLING.md, which this
        # PR stopped vendoring. In an installed archive a relative link there is a
        # dead end, so the mandated checklist cannot be followed. Every reference
        # from a SHIPPED file to an UNSHIPPED doc must be an absolute URL.
        shipped = {e['path'] for e in scaffold.generate_manifest(ROOT)['files']}
        unshipped = ('AGENTS_TOOLING.md', 'BUILD.md', 'BUILD_INGESTION.md',
                     'BUILD_INTERFACE.md', 'TOOLING_INGESTION.md',
                     'TOOLING_INTERFACE.md')
        for doc in unshipped:
            self.assertNotIn(doc, shipped, f'{doc} is workshop-only')
        offenders = []
        for rel in sorted(shipped):
            src = ROOT / rel
            if src.suffix != '.md' or not src.is_file():
                continue
            text = src.read_text(encoding='utf-8', errors='replace')
            for doc in unshipped:
                for form in (f']({doc})', f'](../{doc})', f'](../../{doc})'):
                    if form in text:
                        offenders.append(f'{rel} -> {form}')
        self.assertEqual(offenders, [], f'relative links to workshop-only docs: {offenders}')

    def test_skeleton_and_operating_categories(self):
        files = scaffold.generate_manifest(ROOT)['files']
        by_path = {e['path']: e for e in files}
        # Skeleton seeds present, remapped, and carry a src that differs.
        self.assertEqual(by_path['fha.yaml']['category'], 'skeleton')
        self.assertEqual(by_path['fha.yaml']['src'], 'archive-template/fha.yaml')
        self.assertEqual(by_path['places/places.yaml']['category'], 'skeleton')
        # The five BUILD-mandated docs ship, at the archive ROOT: only the
        # machinery (tools/, design/) is vendored under .fha/. docs/ stays put so
        # its two-way link graph with the rulebooks keeps resolving - see
        # test_docs_stay_at_archive_root.
        for doc in ('docs/GETTING_STARTED.md', 'docs/SETUP_FROM_ZIP.md',
                    'docs/CHEATSHEET.md', 'docs/TROUBLESHOOTING.md',
                    'docs/FILING_CABINET.md'):
            self.assertIn(doc, by_path, doc)
            self.assertEqual(by_path[doc]['category'], 'operating')
        # A vendored operating entry carries a src remap (repo-flat -> archive
        # .fha/); a root-pinned operating entry (SPEC.md) carries none.
        self.assertEqual(by_path['.fha/tools/scaffold.py']['src'], 'tools/scaffold.py')
        self.assertNotIn('src', by_path['SPEC.md'])

    def test_docs_stay_at_archive_root(self):
        # The rulebooks and docs/ are one two-way link graph: README.md links to
        # `docs/GETTING_STARTED.md`, and docs link back to `../SPEC.md`. Vendoring
        # either side under .fha/ alone breaks every one of those links in an
        # installed archive, which has to stay navigable in a file browser. So
        # docs/ installs at the root, unremapped, and only the machinery moves.
        by_path = {e['path']: e for e in scaffold.generate_manifest(ROOT)['files']}
        doc_paths = [p for p in by_path if p.split('/')[0] == 'docs']
        self.assertTrue(doc_paths, 'docs/ must ship')
        for p in doc_paths:
            self.assertNotIn('src', by_path[p], f'{p} must not be remapped')
        self.assertFalse([p for p in by_path if p.startswith('.fha/docs/')],
                         'no doc may be vendored under .fha/')
        # Both ends of the link graph land where the links expect them.
        self.assertIn('README.md', by_path)
        self.assertIn('docs/GETTING_STARTED.md', by_path)
        # Meanwhile the machinery IS vendored.
        self.assertTrue([p for p in by_path if p.startswith('.fha/tools/')])
        self.assertTrue([p for p in by_path if p.startswith('.fha/design/')])


class InstallTest(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self.repo = _make_fake_repo(self.tmp / 'repo')
        self.archive = self.tmp / 'archive'

    def tearDown(self):
        self._tmp.cleanup()

    def test_install_copies_files_and_stamps(self):
        rc = scaffold.run_install(self.archive, self.repo)
        self.assertEqual(rc, EXIT_CLEAN)
        # operating + skeleton landed, remapped correctly
        self.assertTrue((self.archive / 'SPEC.md').is_file())
        self.assertTrue((self.archive / '.fha' / 'tools' /'atool.py').is_file())
        self.assertTrue((self.archive / 'docs' / 'guide.md').is_file())
        self.assertTrue((self.archive / 'fha.yaml').is_file())
        self.assertTrue((self.archive / 'places' / 'places.yaml').is_file())
        self.assertTrue((self.archive / 'sources' / '.gitkeep').is_file())
        # archive-template/ folder itself is never created in the archive
        self.assertFalse((self.archive / 'archive-template').exists())
        # stamp records every copied file's checksum
        stamp = json.loads((self.archive / '.plaintext-version').read_text(encoding='utf-8'))
        self.assertIn('SPEC.md', stamp['files'])
        self.assertIn('fha.yaml', stamp['files'])
        self.assertEqual(stamp['manifest_version'], scaffold.MANIFEST_VERSION)

    def test_install_dry_run_writes_nothing(self):
        rc = scaffold.run_install(self.archive, self.repo, dry_run=True)
        self.assertEqual(rc, EXIT_CLEAN)
        self.assertFalse(self.archive.exists())

    def test_reinstall_refused(self):
        scaffold.run_install(self.archive, self.repo)
        with self.assertRaises(scaffold.ScaffoldError) as ctx:
            scaffold.run_install(self.archive, self.repo)
        self.assertIn('already', str(ctx.exception).lower())

    def test_missing_source_refused_before_writing(self):
        (self.repo / 'tools' / 'atool.py').unlink()  # manifest still lists it
        with self.assertRaises(scaffold.ScaffoldError) as ctx:
            scaffold.run_install(self.archive, self.repo)
        self.assertIn('missing', str(ctx.exception).lower())
        # nothing half-written
        self.assertFalse(self.archive.exists())

    def test_missing_manifest_is_friendly(self):
        (self.repo / 'manifest.json').unlink()
        with self.assertRaises(scaffold.ScaffoldError) as ctx:
            scaffold.run_install(self.archive, self.repo)
        self.assertIn('manifest.json', str(ctx.exception))

    def test_python_too_old_is_a_hard_stop(self):
        with mock.patch.object(scaffold.sys, 'version_info', (3, 9, 0)):
            rc = scaffold._cmd_install(argparse.Namespace(
                archive_path=str(self.archive), repo=str(self.repo), dry_run=False))
        self.assertEqual(rc, EXIT_FAILURE)
        self.assertFalse(self.archive.exists())

    def test_exiftool_missing_is_only_advisory(self):
        with mock.patch('scaffold.shutil.which', return_value=None):
            rc = scaffold.run_install(self.archive, self.repo)
        self.assertEqual(rc, EXIT_CLEAN)  # install still succeeds
        self.assertTrue((self.archive / 'SPEC.md').is_file())


class UpdateToolsTest(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self.repo = _make_fake_repo(self.tmp / 'repo')
        self.archive = self.tmp / 'archive'
        scaffold.run_install(self.archive, self.repo)

    def tearDown(self):
        self._tmp.cleanup()

    def _stamp(self):
        return json.loads((self.archive / '.plaintext-version').read_text(encoding='utf-8'))

    def test_noop_when_current(self):
        rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc, EXIT_CLEAN)
        self.assertFalse((self.archive / '.plaintext-backup').exists())

    def test_stock_change_overwrites_silently(self):
        # Upstream improved atool.py; the archive's copy is still pristine.
        _write(self.repo / 'tools' / 'atool.py', 'print("a tool v2")\n')
        scaffold._write_manifest(self.repo)
        rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc, EXIT_CLEAN)
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("a tool v2")\n')
        self.assertFalse((self.archive / '.plaintext-backup').exists())
        # stamp now records the new checksum
        self.assertEqual(self._stamp()['files']['.fha/tools/atool.py'],
                         scaffold._sha256_file(self.repo / 'tools' / 'atool.py'))

    def test_customized_file_is_backed_up_then_updated(self):
        # Archive owner edited their atool.py; upstream also moved on.
        _write(self.archive / '.fha' / 'tools' /'atool.py', 'print("MY EDIT")\n')
        _write(self.repo / 'tools' / 'atool.py', 'print("a tool v2")\n')
        scaffold._write_manifest(self.repo)
        rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc, EXIT_CLEAN)
        # live file is the new stock
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("a tool v2")\n')
        # the edit survives in the backup
        backups = list((self.archive / '.plaintext-backup').rglob('atool.py'))
        self.assertEqual(len(backups), 1)
        self.assertEqual(backups[0].read_text(encoding='utf-8'), 'print("MY EDIT")\n')

    def test_skeleton_files_are_never_touched(self):
        # The critical safety property: a user's fha.yaml/places.yaml is data, not
        # operating layer - update-tools must leave it exactly as-is, even if
        # upstream's template changed.
        _write(self.archive / 'fha.yaml', 'roots:\n  photos: D:/MyPhotos\n')
        _write(self.archive / 'places' / 'places.yaml', '- id: L-abc\n  name: MyTown\n')
        _write(self.repo / 'archive-template' / 'fha.yaml', 'roots:\n  photos: changed\n')
        scaffold._write_manifest(self.repo)
        scaffold.run_update_tools(self.archive, self.repo)
        self.assertIn('MyPhotos', (self.archive / 'fha.yaml').read_text(encoding='utf-8'))
        self.assertIn('MyTown', (self.archive / 'places' / 'places.yaml').read_text(encoding='utf-8'))
        # never even backed up
        self.assertFalse((self.archive / '.plaintext-backup').exists())

    def test_retired_file_moved_to_backup(self):
        # Inject a recorded tool that the manifest no longer lists.
        retired = self.archive / '.fha' / 'tools' /'oldtool.py'
        _write(retired, 'print("old")\n')
        stamp = self._stamp()
        stamp['files']['.fha/tools/oldtool.py'] = 'deadbeef'
        _write(self.archive / '.plaintext-version', json.dumps(stamp))
        rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc, EXIT_CLEAN)
        self.assertFalse(retired.exists())
        moved = list((self.archive / '.plaintext-backup').rglob('oldtool.py'))
        self.assertEqual(len(moved), 1)
        # and it's dropped from the refreshed stamp
        self.assertNotIn('.fha/tools/oldtool.py', self._stamp()['files'])

    def test_added_file_copied_in(self):
        _write(self.repo / 'tools' / 'newtool.py', 'print("new")\n')
        scaffold._write_manifest(self.repo)
        scaffold.run_update_tools(self.archive, self.repo)
        self.assertTrue((self.archive / '.fha' / 'tools' /'newtool.py').is_file())
        self.assertIn('.fha/tools/newtool.py', self._stamp()['files'])

    def test_dry_run_writes_nothing(self):
        _write(self.archive / '.fha' / 'tools' /'atool.py', 'print("MY EDIT")\n')
        _write(self.repo / 'tools' / 'atool.py', 'print("v2")\n')
        scaffold._write_manifest(self.repo)
        rc = scaffold.run_update_tools(self.archive, self.repo, dry_run=True)
        self.assertEqual(rc, EXIT_CLEAN)
        # the customized file is left exactly as the user had it; no backup made
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("MY EDIT")\n')
        self.assertFalse((self.archive / '.plaintext-backup').exists())

    def test_broken_clone_refused_before_any_mutation(self):
        # A file the manifest lists but the clone no longer ships must abort the
        # update before anything is copied or backed up.
        _write(self.archive / '.fha' / 'tools' /'atool.py', 'print("MY EDIT")\n')  # would be customized
        _write(self.repo / 'tools' / 'newtool.py', 'print("new")\n')
        scaffold._write_manifest(self.repo)            # manifest now lists newtool.py
        (self.repo / 'tools' / 'newtool.py').unlink()  # ...then the source vanishes
        with self.assertRaises(scaffold.ScaffoldError) as ctx:
            scaffold.run_update_tools(self.archive, self.repo)
        self.assertIn('missing', str(ctx.exception).lower())
        # the customized file was NOT moved to backup
        self.assertFalse((self.archive / '.plaintext-backup').exists())
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("MY EDIT")\n')

    def test_partial_failure_does_not_claim_success(self):
        # A per-file failure must not produce a success message or inflate the
        # summary counts (the output stays honest), and must surface the failure.
        _write(self.archive / '.fha' / 'tools' /'atool.py', 'print("MY EDIT")\n')  # customized
        _write(self.repo / 'tools' / 'atool.py', 'print("v2")\n')
        scaffold._write_manifest(self.repo)
        out, err = io.StringIO(), io.StringIO()
        with mock.patch('scaffold.shutil.move', side_effect=OSError('locked')):
            with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
                rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc, EXIT_WARNINGS)
        self.assertNotIn('has been backed up', out.getvalue())          # no false success
        self.assertIn('Done: 0 added, 0 updated, 0 backed up', out.getvalue())  # honest counts
        self.assertIn('could not be updated', err.getvalue())           # failure surfaced
        # the edit is intact (the move failed before touching it); nothing backed up
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("MY EDIT")\n')
        self.assertEqual(list((self.archive / '.plaintext-backup').rglob('atool.py')), [])

    def test_failed_update_keeps_edit_safe_on_retry(self):
        # Regression: a failed customized-file update must NOT record the edited
        # bytes as the installed baseline. If it did, the retry would see
        # disk == recorded, classify the file as pristine stock, and silently
        # overwrite the human's edit with no backup (data loss).
        _write(self.archive / '.fha' / 'tools' /'atool.py', 'print("MY EDIT")\n')
        _write(self.repo / 'tools' / 'atool.py', 'print("v2")\n')
        scaffold._write_manifest(self.repo)
        # Run 1: move fails.
        with mock.patch('scaffold.shutil.move', side_effect=OSError('locked')):
            with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
                self.assertEqual(scaffold.run_update_tools(self.archive, self.repo), EXIT_WARNINGS)
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("MY EDIT")\n')
        # Run 2: move works. The edit must be BACKED UP, not silently overwritten.
        with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
            self.assertEqual(scaffold.run_update_tools(self.archive, self.repo), EXIT_CLEAN)
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("v2")\n')
        backups = list((self.archive / '.plaintext-backup').rglob('atool.py'))
        self.assertEqual(len(backups), 1)
        self.assertEqual(backups[0].read_text(encoding='utf-8'), 'print("MY EDIT")\n')

    def test_failed_retired_move_is_retried_next_run(self):
        # A retired file whose move fails must stay recorded so the next run
        # re-detects and retries it (a successful move drops it from the stamp).
        retired = self.archive / '.fha' / 'tools' /'oldtool.py'
        _write(retired, 'print("old")\n')
        stamp = json.loads((self.archive / '.plaintext-version').read_text(encoding='utf-8'))
        stamp['files']['.fha/tools/oldtool.py'] = 'deadbeef'
        _write(self.archive / '.plaintext-version', json.dumps(stamp))
        with mock.patch('scaffold.shutil.move', side_effect=OSError('locked')):
            with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
                self.assertEqual(scaffold.run_update_tools(self.archive, self.repo), EXIT_WARNINGS)
        self.assertTrue(retired.exists())  # move failed, file still there
        # still recorded → still detectable as retired
        new_stamp = json.loads((self.archive / '.plaintext-version').read_text(encoding='utf-8'))
        self.assertIn('.fha/tools/oldtool.py', new_stamp['files'])
        # retry succeeds and moves it to backup
        with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
            self.assertEqual(scaffold.run_update_tools(self.archive, self.repo), EXIT_CLEAN)
        self.assertFalse(retired.exists())
        self.assertEqual(len(list((self.archive / '.plaintext-backup').rglob('oldtool.py'))), 1)

    def test_no_version_stamp_treats_existing_as_customized(self):
        # An archive whose tools were hand-copied (no install) still must not lose
        # a hand-edit on update.
        (self.archive / '.plaintext-version').unlink()
        _write(self.archive / '.fha' / 'tools' /'atool.py', 'print("HAND EDIT")\n')
        scaffold.run_update_tools(self.archive, self.repo)
        backups = list((self.archive / '.plaintext-backup').rglob('atool.py'))
        self.assertEqual(len(backups), 1)
        self.assertEqual(backups[0].read_text(encoding='utf-8'), 'print("HAND EDIT")\n')


class CmdErrorPathTest(unittest.TestCase):
    """The argparse bridges return friendly exit codes, never tracebacks."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self.repo = _make_fake_repo(self.tmp / 'repo')

    def tearDown(self):
        self._tmp.cleanup()

    def test_update_missing_repo(self):
        rc = scaffold._cmd_update_tools(argparse.Namespace(
            repo=None, root=str(self.tmp), dry_run=False, verbose=False))
        self.assertEqual(rc, EXIT_FAILURE)

    def test_update_not_an_archive(self):
        # root points at a folder with no fha.yaml; no auto-detect either.
        empty = self.tmp / 'not-an-archive'
        empty.mkdir()
        # find_archive_root walks up from CWD; force the no-root branch by passing
        # a root that exists but isn't an archive - _cmd uses the explicit root, so
        # update runs and fails to find a manifest? No: it runs against that root.
        # Instead drop --root and patch find_archive_root to None.
        with mock.patch('scaffold.find_archive_root', return_value=None):
            rc = scaffold._cmd_update_tools(argparse.Namespace(
                repo=str(self.repo), root=None, dry_run=False, verbose=False))
        self.assertEqual(rc, EXIT_FAILURE)

    def test_update_explicit_root_must_be_an_archive(self):
        # A mistyped --root (a real folder, but not an archive) must be refused
        # before any operating-layer file is written into it.
        not_arch = self.tmp / 'not-an-archive'
        not_arch.mkdir()
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            rc = scaffold._cmd_update_tools(argparse.Namespace(
                repo=str(self.repo), root=str(not_arch), dry_run=False, verbose=False))
        self.assertEqual(rc, EXIT_FAILURE)
        self.assertIn('does not look like an archive', err.getvalue())
        self.assertEqual(list(not_arch.iterdir()), [])  # nothing written

    def test_install_bad_repo_is_friendly_exit(self):
        rc = scaffold._cmd_install(argparse.Namespace(
            archive_path=str(self.tmp / 'arch'),
            repo=str(self.tmp / 'no-such-repo'), dry_run=False))
        self.assertEqual(rc, EXIT_FAILURE)


def _make_flat_archive(root: Path, *, with_stamp: bool = True) -> Path:
    """A pre-.fha archive: tools/, docs/, design/ at the root + a flat stamp.

    Note `serve.cmd`: a real pre-.fha archive's launcher names `tools\\fha.py`
    directly and knows nothing about a vendor folder, and `fha`/`fha.cmd` may not
    exist at all - which is exactly what moving tools/ breaks.
    """
    _write(root / 'fha.yaml', 'roots:\n  photos: photos\n  documents: documents\n')
    _write(root / 'SPEC.md', '# SPEC\n')          # root rulebook, stays put
    _write(root / 'CLAUDE.md', '# CLAUDE\n')      # root rulebook, stays put
    _write(root / 'serve.cmd', '@echo off\npy -3 tools\\fha.py serve %*\n')  # stale
    _write(root / 'tools' / 'fha.py', 'print("fha")\n')
    _write(root / 'tools' / 'sub' / 'x.py', 'x = 1\n')
    _write(root / 'docs' / 'guide.md', '# guide\n')        # stays at the root
    _write(root / 'design' / 'styles.css', 'body{}\n')      # vendored (in stamp)
    _write(root / 'design' / 'custom.css', '/* mine */\n')  # skeleton (NOT in stamp)
    _write(root / '.claude' / 'skills' / 's.md', '# skill\n')  # stays at root
    _write(root / 'people' / '.gitkeep', '')                # a record, untouched
    if with_stamp:
        stamp = {
            'manifest_version': '1', 'spec_version': '1.2',
            'installed': '2026-01-01T00:00:00',
            'files': {
                'tools/fha.py': 'aaa', 'tools/sub/x.py': 'bbb',
                'docs/guide.md': 'ccc', 'design/styles.css': 'ddd',
                'SPEC.md': 'eee', '.claude/skills/s.md': 'fff',
            },
        }
        _write(root / '.plaintext-version', json.dumps(stamp))
    return root


def _make_launcher_repo(root: Path) -> Path:
    """A stand-in workshop holding just the current root launchers."""
    _write(root / 'serve.cmd', '@echo off\nif exist ".fha\\tools\\fha.py" (echo new)\n')
    _write(root / 'fha.cmd', '@echo off\nrem .fha probe\n')
    _write(root / 'fha', '#!/bin/sh\n# .fha probe\n')
    return root


class MigrateLayoutTest(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.arc = _make_flat_archive(Path(self._tmp.name) / 'arc')
        self.launchers = _make_launcher_repo(Path(self._tmp.name) / 'workshop')

    def _migrate(self, **kw):
        kw.setdefault('repo_root', self.launchers)
        return scaffold.run_migrate_layout(self.arc, **kw)

    def tearDown(self):
        self._tmp.cleanup()

    def test_moves_subtrees_and_rekeys_stamp(self):
        rc = self._migrate()
        self.assertEqual(rc.exit_code, EXIT_CLEAN)
        # tools/docs/design now under .fha/ ...
        self.assertTrue((self.arc / '.fha' / 'tools' / 'fha.py').is_file())
        self.assertTrue((self.arc / '.fha' / 'tools' / 'sub' / 'x.py').is_file())
        self.assertTrue((self.arc / '.fha' / 'design' / 'styles.css').is_file())
        # ... custom.css rode along (it lives under design/) ...
        self.assertTrue((self.arc / '.fha' / 'design' / 'custom.css').is_file())
        # ... the flat copies are gone ...
        self.assertFalse((self.arc / 'tools').exists())
        self.assertFalse((self.arc / 'design').exists())
        # ... docs/ did NOT move: it is human-facing reading matter whose links
        # point at the root rulebooks and vice versa (see the manifest tests) ...
        self.assertTrue((self.arc / 'docs' / 'guide.md').is_file())
        self.assertFalse((self.arc / '.fha' / 'docs').exists())
        # ... rulebooks, skills, and records stayed at the root ...
        self.assertTrue((self.arc / 'SPEC.md').is_file())
        self.assertTrue((self.arc / '.claude' / 'skills' / 's.md').is_file())
        self.assertTrue((self.arc / 'people' / '.gitkeep').is_file())
        # ... and the stamp was re-keyed: vendored paths prefixed, others intact.
        stamp = json.loads((self.arc / '.plaintext-version').read_text(encoding='utf-8'))
        self.assertIn('.fha/tools/fha.py', stamp['files'])
        self.assertIn('.fha/design/styles.css', stamp['files'])
        self.assertNotIn('tools/fha.py', stamp['files'])
        self.assertIn('SPEC.md', stamp['files'])                 # root doc key intact
        self.assertIn('docs/guide.md', stamp['files'])           # docs key intact
        self.assertIn('.claude/skills/s.md', stamp['files'])     # skills key intact

    def test_dry_run_writes_nothing(self):
        before = sorted(p.relative_to(self.arc).as_posix()
                        for p in self.arc.rglob('*') if p.is_file())
        rc = self._migrate(dry_run=True)
        self.assertEqual(rc.exit_code, EXIT_CLEAN)
        after = sorted(p.relative_to(self.arc).as_posix()
                       for p in self.arc.rglob('*') if p.is_file())
        self.assertEqual(before, after)
        self.assertFalse((self.arc / '.fha').exists())

    def test_idempotent_noop_when_already_migrated(self):
        self._migrate()
        rc = self._migrate()  # second run
        self.assertEqual(rc.exit_code, EXIT_CLEAN)
        self.assertEqual(rc.data['moved'], 0)

    def test_refuses_ambiguous_half_migrated_state(self):
        _write(self.arc / '.fha' / 'tools' / 'fha.py', 'print("dup")\n')  # both exist
        with self.assertRaises(scaffold.ScaffoldError) as ctx:
            self._migrate()
        self.assertIn('refusing', str(ctx.exception).lower())
        self.assertTrue((self.arc / 'tools').exists())  # nothing moved

    def test_no_stamp_hand_copied_archive_still_moves(self):
        (self.arc / '.plaintext-version').unlink()
        rc = self._migrate()
        self.assertEqual(rc.exit_code, EXIT_CLEAN)
        self.assertTrue((self.arc / '.fha' / 'tools' / 'fha.py').is_file())
        self.assertFalse((self.arc / 'tools').exists())

    def test_refreshes_stale_and_missing_root_launchers(self):
        # A pre-.fha serve.cmd runs `tools\fha.py` by name and there is no CLI
        # shim beside it. Move tools/ without replacing them and double-clicking
        # serve.cmd stops working with no `fha` command to fall back on.
        rc = self._migrate()
        self.assertEqual(rc.exit_code, EXIT_CLEAN)
        self.assertEqual(rc.data['launchers_pending'], 0)
        serve = (self.arc / 'serve.cmd').read_text(encoding='utf-8')
        self.assertIn('.fha', serve)                       # refreshed, not stale
        self.assertTrue((self.arc / 'fha.cmd').is_file())  # installed, was absent
        self.assertTrue((self.arc / 'fha').is_file())      # POSIX shim too

    def test_reports_launchers_it_could_not_refresh(self):
        # Running from inside the archive: repo_root is the archive's own vendor
        # folder, which holds no launcher sources. Say so and name the fix rather
        # than leaving a silently broken serve.cmd behind.
        empty = Path(self._tmp.name) / 'empty-repo'
        empty.mkdir()
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            rc = scaffold.run_migrate_layout(self.arc, repo_root=empty)
        # A file that could not be written is exit 1 by this project's
        # convention, and here it is load bearing: tools/ has moved and the
        # archive may have no working launcher left.
        self.assertEqual(rc.exit_code, EXIT_WARNINGS)
        self.assertTrue(rc.data['launchers_pending'])
        out = buf.getvalue()
        self.assertIn('serve.cmd', out)
        self.assertIn('update-tools', out)
        # The move itself still happened - the launcher is a follow-up, not a gate.
        self.assertTrue((self.arc / '.fha' / 'tools' / 'fha.py').is_file())

    def test_up_to_date_launcher_is_left_alone(self):
        _write(self.arc / 'serve.cmd', '@echo off\nrem .fha\\tools already probed\n')
        before = (self.arc / 'serve.cmd').read_text(encoding='utf-8')
        self._migrate()
        self.assertEqual((self.arc / 'serve.cmd').read_text(encoding='utf-8'), before)

    def test_names_capture_host_when_one_is_registered(self):
        # The browser's stored launcher holds an absolute <archive>/tools/fha.py;
        # the move invalidates it and doctor does not inspect it, so this run is
        # the only thing that can tell the owner.
        fake_host = self.arc / 'fake-host.json'
        _write(fake_host, '{}')
        buf = io.StringIO()
        with mock.patch.object(scaffold, '_capture_host_installed',
                               return_value=fake_host), \
                contextlib.redirect_stdout(buf):
            self._migrate()
        out = buf.getvalue()
        self.assertIn('capture --install-host', out)

    def test_dry_run_previews_launcher_and_capture_followups(self):
        fake_host = self.arc / 'fake-host.json'
        _write(fake_host, '{}')
        buf = io.StringIO()
        with mock.patch.object(scaffold, '_capture_host_installed',
                               return_value=fake_host), \
                contextlib.redirect_stdout(buf):
            self._migrate(dry_run=True)
        out = buf.getvalue()
        self.assertIn('serve.cmd', out)
        self.assertIn('capture --install-host', out)
        self.assertFalse((self.arc / '.fha').exists())     # still nothing written

    def test_malformed_stamp_files_value_does_not_traceback(self):
        # A hand-mangled stamp whose `files` is valid JSON but not an object used
        # to raise AttributeError from .items() - AFTER the folders had moved, so
        # the owner saw a traceback out of a mutating command.
        _write(self.arc / '.plaintext-version',
               json.dumps({'manifest_version': '1', 'files': ['tools/fha.py']}))
        rc = self._migrate()
        self.assertEqual(rc.exit_code, EXIT_CLEAN)
        self.assertTrue((self.arc / '.fha' / 'tools' / 'fha.py').is_file())
        stamp = json.loads((self.arc / '.plaintext-version').read_text(encoding='utf-8'))
        self.assertEqual(stamp['files'], {})   # re-stamped clean, not crashed

    def test_ignores_a_capture_host_registered_for_another_archive(self):
        # One host manifest per browser per machine, whoever registered last. A
        # host belonging to archive A must not make migrating archive B tell the
        # owner to re-register - following that would repoint A's host at B.
        other = Path(self._tmp.name) / 'other-archive'
        launcher = Path(self._tmp.name) / 'host-launcher.sh'
        _write(launcher, f'#!/bin/sh\nexec python3 "{other}/tools/fha.py" '
                         f'capture --host --root "{other}"\n')
        manifest = Path(self._tmp.name) / 'host.json'
        _write(manifest, json.dumps({'path': str(launcher)}))

        class _FakeCapture:
            _NATIVE_HOST_NAME = 'host'

            @staticmethod
            def _native_manifest_dir(browser):
                return manifest.parent

        with mock.patch.dict(sys.modules, {'capture': _FakeCapture}):
            self.assertIsNone(scaffold._capture_host_installed(self.arc))
            # ... but a host that DOES name this archive is reported.
            _write(launcher, f'#!/bin/sh\nexec python3 "{self.arc}/tools/fha.py" '
                             f'capture --host --root "{self.arc}"\n')
            self.assertEqual(scaffold._capture_host_installed(self.arc), manifest)

    def test_customized_launcher_is_backed_up_before_refresh(self):
        # update-tools gives these same files checksum-and-backup protection; a
        # migration advertised as preserving customizations must not be weaker.
        _write(self.arc / 'serve.cmd',
               '@echo off\nset FHA_PORT=9999\npy -3 tools\\fha.py serve %*\n')
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            rc = self._migrate()
        self.assertEqual(rc.exit_code, EXIT_CLEAN)
        self.assertEqual(rc.data['launchers_backed_up'], 1)
        kept = list((self.arc / '.plaintext-backup').rglob('serve.cmd'))
        self.assertEqual(len(kept), 1)
        self.assertIn('FHA_PORT=9999', kept[0].read_text(encoding='utf-8'))
        # ... and the live one is now the layout-aware stock copy.
        self.assertIn('.fha', (self.arc / 'serve.cmd').read_text(encoding='utf-8'))
        self.assertIn('serve.cmd', buf.getvalue())

    def test_stock_legacy_launcher_is_replaced_without_a_backup(self):
        # The common case: an untouched pre-.fha launcher. A backup here would be
        # noise, so only a file matching no shipped version earns one.
        stock_legacy = '@echo off\npy -3 tools\\fha.py serve %*\n'
        _write(self.arc / 'serve.cmd', stock_legacy)
        manifest = {'files': [{'path': 'serve.cmd',
                               'sha256': scaffold._sha256_bytes(
                                   stock_legacy.encode())}]}
        with contextlib.redirect_stdout(io.StringIO()):
            rc = scaffold.run_migrate_layout(
                self.arc, repo_root=self.launchers)
        # Without the manifest the legacy copy is unknown, so it IS kept - the
        # safe direction. With it recorded as stock, nothing is quarantined.
        self.assertGreaterEqual(rc.data['launchers_backed_up'], 0)
        refreshed, unavailable, backed_up = scaffold._refresh_root_launchers(
            self.arc, self.launchers, ['serve.cmd'], manifest)
        self.assertEqual(backed_up, [])
        self.assertEqual(unavailable, [])
        self.assertEqual(refreshed, ['serve.cmd'])

    def test_capture_host_prefix_paths_do_not_collide(self):
        # /data/family is a substring of /data/family-old: a containment test
        # would claim the neighbour's host and send the owner to re-register,
        # overwriting that archive's working registration.
        sibling = Path(str(self.arc) + '-old')
        launcher = Path(self._tmp.name) / 'host-launcher.sh'
        _write(launcher, f'#!/bin/sh\nexec python3 "{sibling}/tools/fha.py" '
                         f'capture --host --root "{sibling}"\n')
        manifest = Path(self._tmp.name) / 'host.json'
        _write(manifest, json.dumps({'path': str(launcher)}))

        class _FakeCapture:
            _NATIVE_HOST_NAME = 'host'

            @staticmethod
            def _native_manifest_dir(browser):
                return manifest.parent

        with mock.patch.dict(sys.modules, {'capture': _FakeCapture}):
            self.assertIsNone(scaffold._capture_host_installed(self.arc))

    def test_damaged_manifest_entry_refuses_before_any_move(self):
        # A hand-edited or truncated manifest can hold a null or a bare string.
        # Every consumer reaches for entry['path'], so without a check at the
        # loader this surfaces as an AttributeError - during migrate-layout, that
        # is a traceback AFTER tools/ and design/ have already moved.
        bad = Path(self._tmp.name) / 'bad-repo'
        _write(bad / 'manifest.json', json.dumps(
            {'manifest_version': '1', 'files': [{'path': 'ok.md'}, None]}))
        with self.assertRaises(scaffold.ScaffoldError) as ctx:
            scaffold.load_manifest(bad)
        self.assertIn('damaged entry at position 1', str(ctx.exception))
        # A string entry and a path-less object are refused the same way.
        for broken in ('just-a-string', {'sha256': 'abc'}, {'path': ''}):
            _write(bad / 'manifest.json', json.dumps(
                {'manifest_version': '1', 'files': [broken]}))
            with self.assertRaises(scaffold.ScaffoldError):
                scaffold.load_manifest(bad)

    def test_unreadable_stamp_is_set_aside_not_left_to_block_the_next_step(self):
        # `_load_version_stamp` REFUSES invalid JSON, so "the next update-tools
        # re-stamps" is false for this case - it stops with a delete-and-retry
        # message instead. Repair it here rather than reporting a clean migration
        # over a file that blocks the very next documented step.
        _write(self.arc / '.plaintext-version', '{not json at all')
        buf, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(buf), contextlib.redirect_stderr(err):
            rc = self._migrate()
        self.assertEqual(rc.exit_code, EXIT_WARNINGS)
        self.assertTrue(rc.data['stamp_warning'])
        # Set aside, not deleted, and out of the way of the next update.
        self.assertFalse((self.arc / '.plaintext-version').exists())
        salvaged = list(self.arc.glob('.plaintext-version.unreadable*'))
        self.assertEqual(len(salvaged), 1)
        self.assertIn('{not json at all', salvaged[0].read_text(encoding='utf-8'))
        # Already handled, so it must not be listed as a step still to do.
        self.assertNotIn('Fix the version stamp', buf.getvalue())
        # And the archive is now in a state the next update really can re-stamp.
        self.assertIsNone(scaffold._load_version_stamp(self.arc))
        self.assertIn('update-tools', buf.getvalue() + err.getvalue())

    def test_pending_launchers_make_the_run_a_warning(self):
        # tools/ has moved and no working root launcher was installed: a script
        # driving the migration must not read that as a clean run.
        empty = Path(self._tmp.name) / 'empty-repo-2'
        empty.mkdir()
        with contextlib.redirect_stdout(io.StringIO()):
            rc = scaffold.run_migrate_layout(self.arc, repo_root=empty)
        self.assertTrue(rc.data['launchers_pending'])
        self.assertEqual(rc.exit_code, EXIT_WARNINGS)

    def test_stamp_write_failure_after_migration_is_reported(self):
        # The folders have already moved. Silently swallowing this reports a
        # clean migration over a stamp that still names the pre-move paths, and
        # the next update-tools then treats every one of them as retired.
        buf, err = io.StringIO(), io.StringIO()
        with mock.patch.object(scaffold, '_write_version_stamp',
                               side_effect=OSError('no space left on device')), \
                contextlib.redirect_stdout(buf), \
                contextlib.redirect_stderr(err):
            rc = self._migrate()
        self.assertEqual(rc.exit_code, EXIT_WARNINGS)
        self.assertTrue(rc.data['stamp_warning'])
        self.assertIn('no space left', err.getvalue())
        self.assertIn('update-tools', buf.getvalue() + err.getvalue())
        # The move still happened and is still reported honestly.
        self.assertTrue((self.arc / '.fha' / 'tools' / 'fha.py').is_file())

    def test_version_stamp_write_is_atomic(self):
        # A truncated stamp is invalid JSON, and _load_version_stamp refuses an
        # unreadable stamp outright - so a half-written one turns the next
        # update into a manual repair instead of the promised auto re-stamp.
        stamp_path = self.arc / '.plaintext-version'
        before = stamp_path.read_text(encoding='utf-8')
        with mock.patch.object(Path, 'replace', side_effect=OSError('boom')):
            with self.assertRaises(OSError):
                scaffold._write_version_stamp(self.arc, {'files': {}})
        self.assertEqual(stamp_path.read_text(encoding='utf-8'), before)
        leftovers = list(self.arc.glob('.plaintext-version*fha-tmp'))
        self.assertEqual(leftovers, [], 'the temp file must be cleaned up')

    def test_rollback_failure_names_stranded_paths(self):
        # Rolling back a half-done move can itself fail. Claiming "nothing was
        # left half-moved" then sends the owner to retry a command that cannot
        # succeed, against an archive that is genuinely split in two.
        real_move = scaffold.shutil.move
        calls = {'n': 0}

        def flaky(src, dst):
            calls['n'] += 1
            if calls['n'] == 1:
                return real_move(src, dst)     # tools/ moves
            raise OSError('boom')              # design/ fails, and so does undo

        with mock.patch.object(scaffold.shutil, 'move', side_effect=flaky):
            with self.assertRaises(scaffold.ScaffoldError) as ctx:
                self._migrate()
        msg = str(ctx.exception)
        self.assertIn('HALF-MIGRATED', msg)
        self.assertIn('tools', msg)
        self.assertNotIn('Nothing was left half-moved', msg)


class UpdateLayoutTransitionTest(unittest.TestCase):
    """update-tools across the flat -> .fha/ layout change."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        tmp = Path(self._tmp.name)
        self.repo = _make_fake_repo(tmp / 'repo')
        self.archive = tmp / 'arc'
        scaffold.run_install(self.archive, self.repo)

    def tearDown(self):
        self._tmp.cleanup()

    def _stamp(self):
        return json.loads(
            (self.archive / '.plaintext-version').read_text(encoding='utf-8'))

    def _regress_to_flat_custom_css(self, body='/* MY COLOURS */\n'):
        """Put the archive back in the pre-.fha state for the install-once seed."""
        new = self.archive / '.fha' / 'design' / 'custom.css'
        old = self.archive / 'design' / 'custom.css'
        _write(old, body)
        if new.exists():
            new.unlink()
        stamp = self._stamp()
        stamp['files'].pop('.fha/design/custom.css', None)
        stamp['files']['design/custom.css'] = 'whatever-was-installed'
        _write(self.archive / '.plaintext-version', json.dumps(stamp))
        return old, new

    def test_customized_stylesheet_survives_the_layout_change(self):
        # The regression this guards: the manifest no longer lists the flat path,
        # so it reads as RETIRED and goes to .plaintext-backup/ - and updates never
        # install skeleton entries, so nothing replaces it. The owner's styling
        # would simply be gone from the archive.
        old, new = self._regress_to_flat_custom_css()
        with contextlib.redirect_stdout(io.StringIO()):
            rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc.exit_code, EXIT_CLEAN)
        self.assertTrue(new.is_file(), 'the stylesheet must land at its new path')
        self.assertEqual(new.read_text(encoding='utf-8'), '/* MY COLOURS */\n')
        self.assertFalse(old.exists())
        # Not quarantined, and re-keyed in the stamp.
        backups = list((self.archive / '.plaintext-backup').rglob('custom.css')) \
            if (self.archive / '.plaintext-backup').exists() else []
        self.assertEqual(backups, [])
        self.assertIn('.fha/design/custom.css', self._stamp()['files'])
        self.assertNotIn('design/custom.css', self._stamp()['files'])

    def test_dry_run_previews_the_move_without_making_it(self):
        old, new = self._regress_to_flat_custom_css()
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            scaffold.run_update_tools(self.archive, self.repo, dry_run=True)
        self.assertIn('design/custom.css', buf.getvalue())
        self.assertTrue(old.is_file())      # untouched
        self.assertFalse(new.exists())
        # And the preview must not have called it retired - that is the very
        # outcome the real run avoids.
        self.assertNotIn('no longer part of the plaintext tools', buf.getvalue())

    def test_damaged_workshop_aborts_without_stranding_the_stylesheet(self):
        # The relocation must run AFTER the manifest-source preflight. Moving it
        # first, then aborting on a broken workshop copy, leaves the owner's
        # stylesheet at a path the archive's still-flat site.py never reads - the
        # styling silently gone from a run that otherwise changed nothing.
        old, new = self._regress_to_flat_custom_css()
        # A workshop whose manifest promises a file the folder no longer has:
        # exactly the broken/partial clone the preflight exists to catch.
        _write(self.repo / 'tools' / 'btool.py', 'print("b")\n')
        scaffold._write_manifest(self.repo)
        (self.repo / 'tools' / 'btool.py').unlink()
        with contextlib.redirect_stdout(io.StringIO()):
            with self.assertRaises(scaffold.ScaffoldError) as ctx:
                scaffold.run_update_tools(self.archive, self.repo)
        self.assertIn('missing', str(ctx.exception))
        self.assertTrue(old.is_file(), 'stylesheet must stay where site.py reads it')
        self.assertEqual(old.read_text(encoding='utf-8'), '/* MY COLOURS */\n')
        self.assertFalse(new.exists())

    def test_unstamped_legacy_archive_keeps_its_custom_styles(self):
        # An archive assembled by hand-copying tools/ and design/ has no
        # .plaintext-version at all. Keying the relocation off recorded paths
        # skipped exactly those archives: the new .fha/ layer installed, the
        # owner's CSS left at a path the new site.py no longer reads, exit 0.
        old, new = self._regress_to_flat_custom_css('/* HAND COPIED */\n')
        (self.archive / '.plaintext-version').unlink()
        with contextlib.redirect_stdout(io.StringIO()):
            rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc.exit_code, EXIT_CLEAN)
        self.assertTrue(new.is_file())
        self.assertEqual(new.read_text(encoding='utf-8'), '/* HAND COPIED */\n')
        self.assertFalse(old.exists())

    def test_failed_relocation_fails_the_run_and_leaves_the_stamp_alone(self):
        # A move blocked by a lock or permissions must not be recorded as done:
        # the entry is skeleton, so nothing ever re-checks it, and the stylesheet
        # would sit unused at the old path forever under a green exit code.
        old, new = self._regress_to_flat_custom_css()
        real_move = scaffold.shutil.move

        def flaky(src, dst):
            if 'custom.css' in str(src):
                raise OSError('locked')
            return real_move(src, dst)

        buf = io.StringIO()
        with mock.patch.object(scaffold.shutil, 'move', side_effect=flaky), \
                contextlib.redirect_stdout(buf), \
                contextlib.redirect_stderr(io.StringIO()):
            rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc.exit_code, EXIT_WARNINGS)     # a failure, not a footnote
        self.assertTrue(old.is_file())                    # still where site.py reads it
        self.assertNotIn('Moved your design/custom.css', buf.getvalue())
        files = self._stamp()['files']
        self.assertNotIn('.fha/design/custom.css', files)  # re-key rolled back

    def test_legacy_path_is_not_retired_when_its_replacement_fails(self):
        # A flat -> .fha update retires tools/fha.py while adding
        # .fha/tools/fha.py. If the add fails and the retire proceeds, the
        # archive has no entrypoint at all - and the closing "re-run
        # fha update-tools" advice cannot be followed from inside it.
        flat = self.archive / 'tools' / 'atool.py'
        _write(flat, 'print("legacy")\n')
        stamp = self._stamp()
        stamp['files']['tools/atool.py'] = scaffold._sha256_file(flat)
        _write(self.archive / '.plaintext-version', json.dumps(stamp))
        vendored = self.archive / '.fha' / 'tools' / 'atool.py'
        vendored.unlink()      # force it into 'added', then make the add fail

        real_copy = scaffold.shutil.copy2

        def flaky_copy(src, dst, *a, **kw):
            if 'atool.py' in str(dst):
                raise OSError('disk full')
            return real_copy(src, dst, *a, **kw)

        with mock.patch.object(scaffold.shutil, 'copy2', side_effect=flaky_copy), \
                contextlib.redirect_stdout(io.StringIO()), \
                contextlib.redirect_stderr(io.StringIO()):
            rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc.exit_code, EXIT_WARNINGS)
        self.assertTrue(flat.is_file(), 'the only live copy must survive')
        self.assertFalse(vendored.exists())
        backups = list((self.archive / '.plaintext-backup').rglob('atool.py')) \
            if (self.archive / '.plaintext-backup').exists() else []
        self.assertEqual(backups, [], 'nothing should have been quarantined')

    def test_update_leaves_no_hollow_flat_folders_behind(self):
        # Retiring files one at a time leaves their directories standing. After
        # the layout change that means an empty tools/ still in the archive root -
        # the exact clutter the vendored layout removes, and at a glance
        # indistinguishable from an update that half-failed.
        _write(self.archive / 'tools' / 'atool.py', 'print("legacy")\n')
        _write(self.archive / 'tools' / 'nested' / 'deep.py', 'x = 1\n')
        stamp = self._stamp()
        stamp['files']['tools/atool.py'] = 'aaa'
        stamp['files']['tools/nested/deep.py'] = 'bbb'
        _write(self.archive / '.plaintext-version', json.dumps(stamp))
        with contextlib.redirect_stdout(io.StringIO()):
            scaffold.run_update_tools(self.archive, self.repo)
        self.assertFalse((self.archive / 'tools').exists(),
                         'the emptied flat tools/ husk must go')
        # ... but a directory still holding anything is untouched.
        _write(self.archive / 'tools' / 'atool.py', 'print("again")\n')
        _write(self.archive / 'tools' / 'MY-NOTES.txt', 'keep me\n')
        stamp = self._stamp()
        stamp['files']['tools/atool.py'] = 'aaa'
        _write(self.archive / '.plaintext-version', json.dumps(stamp))
        with contextlib.redirect_stdout(io.StringIO()):
            scaffold.run_update_tools(self.archive, self.repo)
        self.assertTrue((self.archive / 'tools' / 'MY-NOTES.txt').is_file())

    def test_partial_toolset_install_rolls_back_and_keeps_the_flat_tree(self):
        # fha.py puts only its OWN directory on sys.path, so a .fha/tools/ with a
        # good fha.py and a failed sibling is not a degraded toolset - it is an
        # unrunnable one, and the launcher prefers it over the intact flat tree
        # beside it. Even the "re-run update-tools" advice dies on ImportError.
        _write(self.repo / 'tools' / 'btool.py', 'print("b")\n')
        scaffold._write_manifest(self.repo)
        # A genuinely FLAT archive: no vendored copies yet, flat ones recorded.
        # Both movable subtrees are mid-transition, which is the real case and
        # what makes the all-or-nothing property observable.
        shutil.rmtree(self.archive / '.fha')
        _write(self.archive / 'design' / 'custom.css', '/* mine */\n')
        stamp = self._stamp()
        for key in [k for k in stamp['files'] if k.startswith('.fha/')]:
            stamp['files'].pop(key)
        for name in ('atool.py', 'btool.py'):
            flat = self.archive / 'tools' / name
            _write(flat, f'print("legacy {name}")\n')
            stamp['files'][f'tools/{name}'] = scaffold._sha256_file(flat)
        _write(self.archive / '.plaintext-version', json.dumps(stamp))

        real_copy = scaffold.shutil.copy2

        def flaky_copy(src, dst, *a, **kw):
            if 'btool.py' in str(dst):
                raise OSError('disk full')
            return real_copy(src, dst, *a, **kw)

        buf = io.StringIO()
        with mock.patch.object(scaffold.shutil, 'copy2', side_effect=flaky_copy), \
                contextlib.redirect_stdout(buf), \
                contextlib.redirect_stderr(io.StringIO()):
            rc = scaffold.run_update_tools(self.archive, self.repo)

        self.assertEqual(rc.exit_code, EXIT_WARNINGS)
        # The half-built vendored toolset is gone entirely - not left for the
        # launcher to prefer over the working one.
        self.assertFalse((self.archive / '.fha' / 'tools' / 'atool.py').exists())
        self.assertFalse((self.archive / '.fha' / 'tools' / 'btool.py').exists())
        # ... and the flat tree that still works is intact and un-retired.
        self.assertEqual(
            (self.archive / 'tools' / 'atool.py').read_text(encoding='utf-8'),
            'print("legacy atool.py")\n')
        self.assertFalse((self.archive / '.fha' / 'tools').exists(),
                         'no half-built vendored toolset may remain')
        # All-or-nothing: design/ must NOT have completed and retired its flat
        # copy, because the archive is now running from flat tools/, whose
        # site.py reads flat design/.
        self.assertTrue((self.archive / 'design' / 'custom.css').is_file())
        self.assertFalse((self.archive / '.fha' / 'design').exists())
        self.assertTrue((self.archive / 'tools' / 'btool.py').is_file())
        backups = list((self.archive / '.plaintext-backup').rglob('atool.py')) \
            if (self.archive / '.plaintext-backup').exists() else []
        self.assertEqual(backups, [], 'nothing should have been quarantined')
        self.assertIn('exactly as it was', buf.getvalue())

    def test_owner_added_design_assets_ride_along_with_the_stylesheet(self):
        # A customized custom.css routinely references siblings the manifest never
        # lists. Relative CSS URLs resolve beside the stylesheet, so an asset left
        # at flat design/ vanishes from the rebuilt site under an exit 0.
        self._regress_to_flat_custom_css('/* mine */\n')
        _write(self.archive / 'design' / 'banner.png', 'PNGDATA')
        _write(self.archive / 'design' / 'fonts' / 'my.woff2', 'FONT')
        with contextlib.redirect_stdout(io.StringIO()):
            rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc.exit_code, EXIT_CLEAN)
        vendored = self.archive / '.fha' / 'design'
        self.assertEqual((vendored / 'custom.css').read_text(encoding='utf-8'),
                         '/* mine */\n')
        self.assertEqual((vendored / 'banner.png').read_text(encoding='utf-8'),
                         'PNGDATA')
        self.assertEqual((vendored / 'fonts' / 'my.woff2').read_text(encoding='utf-8'),
                         'FONT')
        # Nothing of the owner's is left stranded at the dead flat path.
        self.assertFalse((self.archive / 'design' / 'banner.png').exists())

    def test_two_stylesheet_copies_are_reported_not_silently_skipped(self):
        # An interrupted or hand-performed transition can leave both copies. The
        # tools read only the vendored one, so the flat edits are present but
        # inert - the exact failure that must not pass under an exit 0.
        _write(self.archive / 'design' / 'custom.css', '/* MY FLAT EDITS */\n')
        _write(self.archive / '.fha' / 'design' / 'custom.css', '/* vendored */\n')
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf), contextlib.redirect_stderr(buf):
            rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc.exit_code, EXIT_WARNINGS)
        self.assertIn('NOT in use', buf.getvalue())
        # The live copy is untouched...
        self.assertEqual(
            (self.archive / '.fha' / 'design' / 'custom.css').read_text(encoding='utf-8'),
            '/* vendored */\n')
        # ...and the inert one is kept in the backup, not left looking active.
        self.assertFalse((self.archive / 'design' / 'custom.css').exists())
        kept = list((self.archive / '.plaintext-backup').rglob('custom.css'))
        self.assertEqual(len(kept), 1)
        self.assertEqual(kept[0].read_text(encoding='utf-8'), '/* MY FLAT EDITS */\n')

    def test_identical_stylesheet_copies_are_not_reported_as_a_conflict(self):
        for path in (self.archive / 'design' / 'custom.css',
                     self.archive / '.fha' / 'design' / 'custom.css'):
            _write(path, '/* same */\n')
        with contextlib.redirect_stdout(io.StringIO()):
            rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc.exit_code, EXIT_CLEAN)

    def test_new_upstream_seed_lands_but_a_deleted_one_stays_deleted(self):
        # Install-once means "never overwrite", not "never deliver": a seed added
        # upstream after this archive was made must still arrive. But one the
        # owner deleted is RECORDED in the stamp, and must not come back.
        # A seed that appears upstream AFTER this archive was created.
        _write(self.repo / 'archive-template' / '.gitattributes',
               'fha text eol=lf\n')
        scaffold._write_manifest(self.repo)
        self.assertFalse((self.archive / '.gitattributes').exists())

        # ...and one the owner deliberately deleted, which the stamp records.
        deleted = self.archive / 'fha.yaml'
        recorded = self._stamp()['files'].get('fha.yaml')
        self.assertIsNotNone(recorded, 'fixture: fha.yaml should be a seed')
        deleted.unlink()

        with contextlib.redirect_stdout(io.StringIO()):
            scaffold.run_update_tools(self.archive, self.repo)

        # Never delivered before -> delivered now.
        self.assertTrue((self.archive / '.gitattributes').is_file())
        self.assertIn('fha text eol=lf',
                      (self.archive / '.gitattributes').read_text(encoding='utf-8'))
        # Deliberately deleted (and recorded) -> stays gone.
        self.assertFalse(deleted.exists())

    def test_a_delivered_seed_is_recorded_so_it_is_not_redelivered(self):
        # Unrecorded means "never delivered", so a later run would re-deliver a
        # seed the owner had deliberately deleted - the exact opposite of the
        # install-once guarantee.
        _write(self.repo / 'archive-template' / '.gitattributes',
               'fha text eol=lf\n')
        scaffold._write_manifest(self.repo)
        with contextlib.redirect_stdout(io.StringIO()):
            scaffold.run_update_tools(self.archive, self.repo)
        seed = self.archive / '.gitattributes'
        self.assertTrue(seed.is_file())
        self.assertIn('.gitattributes', self._stamp()['files'])

        # Now the owner deletes it on purpose. It must stay gone.
        seed.unlink()
        with contextlib.redirect_stdout(io.StringIO()):
            scaffold.run_update_tools(self.archive, self.repo)
        self.assertFalse(seed.exists())

    def test_failed_style_restore_is_not_swept_into_the_backup(self):
        # When a rollback cannot move custom.css back, the vendored copy is the
        # owner's ONLY one. Quarantining it would take their stylesheet away from
        # an archive that is otherwise being restored untouched.
        _write(self.repo / 'tools' / 'btool.py', 'print("b")\n')
        scaffold._write_manifest(self.repo)
        shutil.rmtree(self.archive / '.fha')
        _write(self.archive / 'design' / 'custom.css', '/* ONLY COPY */\n')
        stamp = self._stamp()
        for key in [k for k in stamp['files'] if k.startswith('.fha/')]:
            stamp['files'].pop(key)
        for name in ('atool.py', 'btool.py'):
            flat = self.archive / 'tools' / name
            _write(flat, f'print("legacy {name}")\n')
            stamp['files'][f'tools/{name}'] = scaffold._sha256_file(flat)
        _write(self.archive / '.plaintext-version', json.dumps(stamp))

        real_copy, real_move = scaffold.shutil.copy2, scaffold.shutil.move

        def flaky_copy(src, dst, *a, **kw):
            if 'btool.py' in str(dst):
                raise OSError('disk full')
            return real_copy(src, dst, *a, **kw)

        def flaky_move(src, dst, *a, **kw):
            # Fail only the ROLLBACK of the stylesheet, not its forward move.
            if 'custom.css' in str(src) and '.fha' in str(src):
                raise OSError('locked')
            return real_move(src, dst, *a, **kw)

        buf = io.StringIO()
        with mock.patch.object(scaffold.shutil, 'copy2', side_effect=flaky_copy), \
                mock.patch.object(scaffold.shutil, 'move', side_effect=flaky_move), \
                contextlib.redirect_stdout(buf), \
                contextlib.redirect_stderr(buf):
            rc = scaffold.run_update_tools(self.archive, self.repo)

        self.assertEqual(rc.exit_code, EXIT_WARNINGS)
        # The only copy still exists somewhere, with its content intact...
        found = [p for p in self.archive.rglob('custom.css') if p.is_file()]
        self.assertTrue(found, 'the owner\'s only stylesheet must still exist')
        self.assertTrue(
            any(p.read_text(encoding='utf-8') == '/* ONLY COPY */\n' for p in found))
        # ...and it was NOT quarantined into the backup folder.
        self.assertEqual(
            [p for p in found if '.plaintext-backup' in p.as_posix()], [])
        # The run says plainly that something needs a hand.
        self.assertIn('could not be moved back', buf.getvalue())

    def test_rollback_clears_a_preexisting_partial_vendor_tree(self):
        # An interrupted earlier attempt can leave a partial .fha/tools/ whose
        # files are manifest-CURRENT. Those never enter installed_ok, so a
        # rollback that removes only this run's installs would leave exactly the
        # incomplete vendored tree the launcher prefers over the intact flat one.
        _write(self.repo / 'tools' / 'btool.py', 'print("b")\n')
        scaffold._write_manifest(self.repo)
        shutil.rmtree(self.archive / '.fha')
        _write(self.archive / 'design' / 'custom.css', '/* mine */\n')
        stamp = self._stamp()
        for key in [k for k in stamp['files'] if k.startswith('.fha/')]:
            stamp['files'].pop(key)
        for name in ('atool.py', 'btool.py'):
            flat = self.archive / 'tools' / name
            _write(flat, f'print("legacy {name}")\n')
            stamp['files'][f'tools/{name}'] = scaffold._sha256_file(flat)
        _write(self.archive / '.plaintext-version', json.dumps(stamp))
        # The relic of the interrupted attempt: byte-identical to stock, so the
        # planner classifies it "current" and never touches it.
        relic = self.archive / '.fha' / 'tools' / 'atool.py'
        relic.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(self.repo / 'tools' / 'atool.py', relic)

        real_copy = scaffold.shutil.copy2

        def flaky_copy(src, dst, *a, **kw):
            if 'btool.py' in str(dst):
                raise OSError('disk full')
            return real_copy(src, dst, *a, **kw)

        with mock.patch.object(scaffold.shutil, 'copy2', side_effect=flaky_copy), \
                contextlib.redirect_stdout(io.StringIO()), \
                contextlib.redirect_stderr(io.StringIO()):
            rc = scaffold.run_update_tools(self.archive, self.repo)

        self.assertEqual(rc.exit_code, EXIT_WARNINGS)
        # No partial vendored tree survives for the launcher to prefer...
        self.assertFalse((self.archive / '.fha').exists())
        # ...the relic was quarantined, not deleted...
        self.assertEqual(
            len(list((self.archive / '.plaintext-backup').rglob('atool.py'))), 1)
        # ...and the flat toolset is intact.
        self.assertEqual(
            (self.archive / 'tools' / 'atool.py').read_text(encoding='utf-8'),
            'print("legacy atool.py")\n')
        self.assertTrue((self.archive / 'tools' / 'btool.py').is_file())

    def test_unstamped_flat_tools_are_retired_not_silently_shadowed(self):
        # A hand-copied archive has no stamp, so nothing is "recorded" to retire.
        # Installing .fha/tools/ and leaving the flat tree means the launcher
        # prefers the new one and the owner's customized flat tools silently stop
        # taking effect - under an exit 0 that just promised a backup.
        _write(self.archive / 'tools' / 'atool.py', 'print("MY EDIT")\n')
        (self.archive / '.plaintext-version').unlink()
        with contextlib.redirect_stdout(io.StringIO()):
            rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc.exit_code, EXIT_CLEAN)
        # The shadowed copy was moved aside, and its content preserved.
        self.assertFalse((self.archive / 'tools' / 'atool.py').exists())
        kept = list((self.archive / '.plaintext-backup').rglob('atool.py'))
        self.assertEqual(len(kept), 1)
        self.assertEqual(kept[0].read_text(encoding='utf-8'), 'print("MY EDIT")\n')
        self.assertTrue((self.archive / '.fha' / 'tools' / 'atool.py').is_file())

    def test_records_are_never_swept_up_by_the_legacy_scan(self):
        # The disk-driven scan must only ever see operating relics under a
        # vendored root - never a record, never a file the human put there.
        _write(self.archive / 'people' / 'someone.md', '# a record\n')
        _write(self.archive / 'tools' / 'MY-SCRATCH.txt', 'my notes\n')
        (self.archive / '.plaintext-version').unlink()
        with contextlib.redirect_stdout(io.StringIO()):
            scaffold.run_update_tools(self.archive, self.repo)
        self.assertTrue((self.archive / 'people' / 'someone.md').is_file())
        # No manifest counterpart -> not a relic -> untouched.
        self.assertTrue((self.archive / 'tools' / 'MY-SCRATCH.txt').is_file())

    def test_malformed_stamp_files_value_does_not_traceback(self):
        stamp = self._stamp()
        stamp['files'] = 'not-an-object'




        _write(self.archive / '.plaintext-version', json.dumps(stamp))
        with contextlib.redirect_stdout(io.StringIO()):
            rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertIn(rc.exit_code, (EXIT_CLEAN, EXIT_WARNINGS))
        self.assertIsInstance(self._stamp()['files'], dict)


if __name__ == '__main__':
    unittest.main()
