"""
Tests for tools/scaffold.py - `fha install` and `fha update-tools` (BUILD.md M9).

Two layers:
  1. A manifest-sync guard that recomputes the operating-layer manifest from the
     real repo and asserts the committed manifest.json still matches it - so a PR
     that changes a tool/doc/skeleton file but forgets to regenerate fails here.
  2. Behavior tests against a small, hand-built FAKE repo (no .git/, proving the
     git-free / zip install path) and throwaway archives, exercising install,
     re-install refusal, the four update outcomes (add/stock/customized/retired),
     the critical skeleton-is-never-touched safety property, dry-run no-ops, and
     the friendly error paths.

Run: python -m unittest tests.test_scaffold -v
"""

import argparse
import contextlib
import io
import json
import os
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'tools'))

import scaffold
from _lib import EXIT_CLEAN, EXIT_FAILURE, EXIT_WARNINGS


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='utf-8')


def _make_fake_repo(repo: Path) -> Path:
    """Build a minimal public-repo clone: 3 operating files + 3 skeleton seeds.

    Deliberately tiny so the tests are fast and every file's role is obvious. No
    .git/ is created anywhere - install/update working against this directory is
    itself the proof of the zip-based, git-free path (BUILD.md M9.1).
    """
    _write(repo / 'SPEC.md', '# SPEC\n\n**Version 9.9 - 2026-01-01**\n\nbody\n')
    _write(repo / 'tools' / 'atool.py', 'print("a tool")\n')
    _write(repo / 'docs' / 'guide.md', '# Guide\n')
    # bytecode that must NOT enter the manifest
    _write(repo / 'tools' / '__pycache__' / 'atool.cpython-312.pyc', 'junk\n')
    # skeleton (remapped from archive-template/ → archive root)
    _write(repo / 'archive-template' / 'fha.yaml', 'roots:\n  photos: photos\n')
    _write(repo / 'archive-template' / 'places' / 'places.yaml', '# places\n')
    _write(repo / 'archive-template' / 'sources' / '.gitkeep', '')
    _write(repo / 'archive-template' / 'README.md', 'template readme - excluded\n')
    # The install-once skeleton override that lives UNDER an operating subtree,
    # so it is the one seed whose archive path moves with the vendor layout.
    _write(repo / 'design' / 'custom.css', '/* stock */\n')
    scaffold._write_manifest(repo)
    return repo


class ManifestSyncTest(unittest.TestCase):
    """The committed manifest.json must match what the repo currently contains."""

    @unittest.skipIf(sys.platform == 'win32',
                     'git core.autocrlf rewrites tracked LF files (e.g. '
                     'design/custom.css, serve.cmd) to CRLF on a Windows '
                     'checkout, so regenerated byte-hashes differ from the '
                     'LF-based committed manifest; CI (Linux) checks currency.')
    def test_committed_manifest_is_current(self):
        committed = json.loads((ROOT / 'manifest.json').read_text(encoding='utf-8'))
        regenerated = scaffold.generate_manifest(ROOT)
        # `generated` is a date stamp that legitimately changes day to day; the
        # contract is the file set + checksums + versions.
        self.assertEqual(committed['manifest_version'], regenerated['manifest_version'])
        self.assertEqual(committed['spec_version'], regenerated['spec_version'])
        self.assertEqual(
            committed['files'], regenerated['files'],
            'manifest.json is out of date - run '
            '`python tools/scaffold.py write-manifest --repo .` and commit the result.',
        )

    def test_manifest_excludes_repo_furniture(self):
        paths = {e['path'] for e in scaffold.generate_manifest(ROOT)['files']}
        # Public-repo furniture that must never enter an archive: PRIVACY.md is the
        # "no real data" policy (contradictory inside a real archive), and the
        # release checklist / packing list / template's own readme are spec-repo
        # maintenance.
        for furniture in ('PRIVACY.md', 'RELEASE_CHECKLIST.md',
                          'manifest.json', 'archive-template/README.md'):
            self.assertNotIn(furniture, paths)
        # No bytecode, no example/test furniture.
        self.assertFalse(any('__pycache__' in p or p.endswith('.pyc') for p in paths))
        self.assertFalse(any(p.startswith(('example-archive/', 'tests/', 'archive-template/'))
                             for p in paths))

    def test_manifest_includes_operating_extras(self):
        paths = {e['path'] for e in scaffold.generate_manifest(ROOT)['files']}
        # Project orientation + the agent's workflow procedures ship into archives.
        self.assertIn('README.md', paths)
        self.assertIn('.claude/skills/README.md', paths)
        # but the spec-repo's own agent config does not.
        self.assertNotIn('.claude/settings.json', paths)

    def test_manifest_excludes_builder_docs(self):
        # The tool-BUILDING docs are not vendored into an archive: no tool reads
        # them at run time and a genealogist never needs them (workshop-only).
        paths = {e['path'] for e in scaffold.generate_manifest(ROOT)['files']}
        for builder in ('BUILD.md', 'BUILD_INGESTION.md', 'BUILD_INTERFACE.md',
                        'TOOLING_INGESTION.md', 'TOOLING_INTERFACE.md',
                        'AGENTS_TOOLING.md'):
            self.assertNotIn(builder, paths, builder)
        # The operating spec/agent docs that DO ship stay.
        for shipped in ('SPEC.md', 'TOOLING.md', 'AGENTS.md', 'CLAUDE.md', 'README.md'):
            self.assertIn(shipped, paths, shipped)

    def test_manifest_includes_launchers(self):
        # plan 17 + archive-layout: the double-clickable workbench launcher AND
        # the terminal CLI shims all ship into every archive - BOTH platforms'
        # shims regardless of the installing OS, because an archive is a portable
        # folder that may well be opened on a different machine than it was made
        # on. All are layout-agnostic - they probe .fha/tools/ first, then
        # tools/ - so one vendored file works flat or consolidated under .fha/.
        entries = {e['path']: e for e in scaffold.generate_manifest(ROOT)['files']}
        for launcher in ('serve.cmd', 'fha.cmd', 'fha'):
            self.assertIn(launcher, entries, launcher)
            self.assertEqual(entries[launcher]['category'], 'operating')
        serve = (ROOT / 'serve.cmd').read_text(encoding='utf-8')
        self.assertIn(r'tools\fha.py serve', serve)        # flat fallback
        self.assertIn(r'.fha\tools\fha.py serve', serve)   # consolidated
        fha_cmd = (ROOT / 'fha.cmd').read_text(encoding='utf-8')
        self.assertIn(r'.fha\tools\fha.py', fha_cmd)

    def test_posix_launcher_is_usable(self):
        # Without this file, every `fha ...` example in the guides is a
        # `command not found` on macOS and Linux - including the very first
        # post-install health check.
        posix = ROOT / 'fha'
        self.assertTrue(posix.is_file(), 'the POSIX `fha` launcher must ship')
        text = posix.read_text(encoding='utf-8')
        self.assertTrue(text.startswith('#!/bin/sh'), 'needs a shebang')
        self.assertIn('.fha/tools/fha.py', text)   # consolidated, probed first
        self.assertIn('tools/fha.py', text)        # flat fallback
        # LF-only: .gitattributes pins it so a Windows checkout cannot produce a
        # CRLF script that /bin/sh chokes on (and that would break its checksum).
        self.assertNotIn(b'\r\n', posix.read_bytes())
        if os.name != 'nt':
            self.assertTrue(os.access(posix, os.X_OK),
                            'the POSIX launcher must be executable')

    def test_skeleton_and_operating_categories(self):
        files = scaffold.generate_manifest(ROOT)['files']
        by_path = {e['path']: e for e in files}
        # Skeleton seeds present, remapped, and carry a src that differs.
        self.assertEqual(by_path['fha.yaml']['category'], 'skeleton')
        self.assertEqual(by_path['fha.yaml']['src'], 'archive-template/fha.yaml')
        self.assertEqual(by_path['places/places.yaml']['category'], 'skeleton')
        # The five BUILD-mandated docs ship, at the archive ROOT: only the
        # machinery (tools/, design/) is vendored under .fha/. docs/ stays put so
        # its two-way link graph with the rulebooks keeps resolving - see
        # test_docs_stay_at_archive_root.
        for doc in ('docs/GETTING_STARTED.md', 'docs/SETUP_FROM_ZIP.md',
                    'docs/CHEATSHEET.md', 'docs/TROUBLESHOOTING.md',
                    'docs/FILING_CABINET.md'):
            self.assertIn(doc, by_path, doc)
            self.assertEqual(by_path[doc]['category'], 'operating')
        # A vendored operating entry carries a src remap (repo-flat -> archive
        # .fha/); a root-pinned operating entry (SPEC.md) carries none.
        self.assertEqual(by_path['.fha/tools/scaffold.py']['src'], 'tools/scaffold.py')
        self.assertNotIn('src', by_path['SPEC.md'])

    def test_docs_stay_at_archive_root(self):
        # The rulebooks and docs/ are one two-way link graph: README.md links to
        # `docs/GETTING_STARTED.md`, and docs link back to `../SPEC.md`. Vendoring
        # either side under .fha/ alone breaks every one of those links in an
        # installed archive, which has to stay navigable in a file browser. So
        # docs/ installs at the root, unremapped, and only the machinery moves.
        by_path = {e['path']: e for e in scaffold.generate_manifest(ROOT)['files']}
        doc_paths = [p for p in by_path if p.split('/')[0] == 'docs']
        self.assertTrue(doc_paths, 'docs/ must ship')
        for p in doc_paths:
            self.assertNotIn('src', by_path[p], f'{p} must not be remapped')
        self.assertFalse([p for p in by_path if p.startswith('.fha/docs/')],
                         'no doc may be vendored under .fha/')
        # Both ends of the link graph land where the links expect them.
        self.assertIn('README.md', by_path)
        self.assertIn('docs/GETTING_STARTED.md', by_path)
        # Meanwhile the machinery IS vendored.
        self.assertTrue([p for p in by_path if p.startswith('.fha/tools/')])
        self.assertTrue([p for p in by_path if p.startswith('.fha/design/')])


class InstallTest(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self.repo = _make_fake_repo(self.tmp / 'repo')
        self.archive = self.tmp / 'archive'

    def tearDown(self):
        self._tmp.cleanup()

    def test_install_copies_files_and_stamps(self):
        rc = scaffold.run_install(self.archive, self.repo)
        self.assertEqual(rc, EXIT_CLEAN)
        # operating + skeleton landed, remapped correctly
        self.assertTrue((self.archive / 'SPEC.md').is_file())
        self.assertTrue((self.archive / '.fha' / 'tools' /'atool.py').is_file())
        self.assertTrue((self.archive / 'docs' / 'guide.md').is_file())
        self.assertTrue((self.archive / 'fha.yaml').is_file())
        self.assertTrue((self.archive / 'places' / 'places.yaml').is_file())
        self.assertTrue((self.archive / 'sources' / '.gitkeep').is_file())
        # archive-template/ folder itself is never created in the archive
        self.assertFalse((self.archive / 'archive-template').exists())
        # stamp records every copied file's checksum
        stamp = json.loads((self.archive / '.plaintext-version').read_text(encoding='utf-8'))
        self.assertIn('SPEC.md', stamp['files'])
        self.assertIn('fha.yaml', stamp['files'])
        self.assertEqual(stamp['manifest_version'], scaffold.MANIFEST_VERSION)

    def test_install_dry_run_writes_nothing(self):
        rc = scaffold.run_install(self.archive, self.repo, dry_run=True)
        self.assertEqual(rc, EXIT_CLEAN)
        self.assertFalse(self.archive.exists())

    def test_reinstall_refused(self):
        scaffold.run_install(self.archive, self.repo)
        with self.assertRaises(scaffold.ScaffoldError) as ctx:
            scaffold.run_install(self.archive, self.repo)
        self.assertIn('already', str(ctx.exception).lower())

    def test_missing_source_refused_before_writing(self):
        (self.repo / 'tools' / 'atool.py').unlink()  # manifest still lists it
        with self.assertRaises(scaffold.ScaffoldError) as ctx:
            scaffold.run_install(self.archive, self.repo)
        self.assertIn('missing', str(ctx.exception).lower())
        # nothing half-written
        self.assertFalse(self.archive.exists())

    def test_missing_manifest_is_friendly(self):
        (self.repo / 'manifest.json').unlink()
        with self.assertRaises(scaffold.ScaffoldError) as ctx:
            scaffold.run_install(self.archive, self.repo)
        self.assertIn('manifest.json', str(ctx.exception))

    def test_python_too_old_is_a_hard_stop(self):
        with mock.patch.object(scaffold.sys, 'version_info', (3, 9, 0)):
            rc = scaffold._cmd_install(argparse.Namespace(
                archive_path=str(self.archive), repo=str(self.repo), dry_run=False))
        self.assertEqual(rc, EXIT_FAILURE)
        self.assertFalse(self.archive.exists())

    def test_exiftool_missing_is_only_advisory(self):
        with mock.patch('scaffold.shutil.which', return_value=None):
            rc = scaffold.run_install(self.archive, self.repo)
        self.assertEqual(rc, EXIT_CLEAN)  # install still succeeds
        self.assertTrue((self.archive / 'SPEC.md').is_file())


class UpdateToolsTest(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self.repo = _make_fake_repo(self.tmp / 'repo')
        self.archive = self.tmp / 'archive'
        scaffold.run_install(self.archive, self.repo)

    def tearDown(self):
        self._tmp.cleanup()

    def _stamp(self):
        return json.loads((self.archive / '.plaintext-version').read_text(encoding='utf-8'))

    def test_noop_when_current(self):
        rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc, EXIT_CLEAN)
        self.assertFalse((self.archive / '.plaintext-backup').exists())

    def test_stock_change_overwrites_silently(self):
        # Upstream improved atool.py; the archive's copy is still pristine.
        _write(self.repo / 'tools' / 'atool.py', 'print("a tool v2")\n')
        scaffold._write_manifest(self.repo)
        rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc, EXIT_CLEAN)
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("a tool v2")\n')
        self.assertFalse((self.archive / '.plaintext-backup').exists())
        # stamp now records the new checksum
        self.assertEqual(self._stamp()['files']['.fha/tools/atool.py'],
                         scaffold._sha256_file(self.repo / 'tools' / 'atool.py'))

    def test_customized_file_is_backed_up_then_updated(self):
        # Archive owner edited their atool.py; upstream also moved on.
        _write(self.archive / '.fha' / 'tools' /'atool.py', 'print("MY EDIT")\n')
        _write(self.repo / 'tools' / 'atool.py', 'print("a tool v2")\n')
        scaffold._write_manifest(self.repo)
        rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc, EXIT_CLEAN)
        # live file is the new stock
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("a tool v2")\n')
        # the edit survives in the backup
        backups = list((self.archive / '.plaintext-backup').rglob('atool.py'))
        self.assertEqual(len(backups), 1)
        self.assertEqual(backups[0].read_text(encoding='utf-8'), 'print("MY EDIT")\n')

    def test_skeleton_files_are_never_touched(self):
        # The critical safety property: a user's fha.yaml/places.yaml is data, not
        # operating layer - update-tools must leave it exactly as-is, even if
        # upstream's template changed.
        _write(self.archive / 'fha.yaml', 'roots:\n  photos: D:/MyPhotos\n')
        _write(self.archive / 'places' / 'places.yaml', '- id: L-abc\n  name: MyTown\n')
        _write(self.repo / 'archive-template' / 'fha.yaml', 'roots:\n  photos: changed\n')
        scaffold._write_manifest(self.repo)
        scaffold.run_update_tools(self.archive, self.repo)
        self.assertIn('MyPhotos', (self.archive / 'fha.yaml').read_text(encoding='utf-8'))
        self.assertIn('MyTown', (self.archive / 'places' / 'places.yaml').read_text(encoding='utf-8'))
        # never even backed up
        self.assertFalse((self.archive / '.plaintext-backup').exists())

    def test_retired_file_moved_to_backup(self):
        # Inject a recorded tool that the manifest no longer lists.
        retired = self.archive / '.fha' / 'tools' /'oldtool.py'
        _write(retired, 'print("old")\n')
        stamp = self._stamp()
        stamp['files']['.fha/tools/oldtool.py'] = 'deadbeef'
        _write(self.archive / '.plaintext-version', json.dumps(stamp))
        rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc, EXIT_CLEAN)
        self.assertFalse(retired.exists())
        moved = list((self.archive / '.plaintext-backup').rglob('oldtool.py'))
        self.assertEqual(len(moved), 1)
        # and it's dropped from the refreshed stamp
        self.assertNotIn('.fha/tools/oldtool.py', self._stamp()['files'])

    def test_added_file_copied_in(self):
        _write(self.repo / 'tools' / 'newtool.py', 'print("new")\n')
        scaffold._write_manifest(self.repo)
        scaffold.run_update_tools(self.archive, self.repo)
        self.assertTrue((self.archive / '.fha' / 'tools' /'newtool.py').is_file())
        self.assertIn('.fha/tools/newtool.py', self._stamp()['files'])

    def test_dry_run_writes_nothing(self):
        _write(self.archive / '.fha' / 'tools' /'atool.py', 'print("MY EDIT")\n')
        _write(self.repo / 'tools' / 'atool.py', 'print("v2")\n')
        scaffold._write_manifest(self.repo)
        rc = scaffold.run_update_tools(self.archive, self.repo, dry_run=True)
        self.assertEqual(rc, EXIT_CLEAN)
        # the customized file is left exactly as the user had it; no backup made
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("MY EDIT")\n')
        self.assertFalse((self.archive / '.plaintext-backup').exists())

    def test_broken_clone_refused_before_any_mutation(self):
        # A file the manifest lists but the clone no longer ships must abort the
        # update before anything is copied or backed up.
        _write(self.archive / '.fha' / 'tools' /'atool.py', 'print("MY EDIT")\n')  # would be customized
        _write(self.repo / 'tools' / 'newtool.py', 'print("new")\n')
        scaffold._write_manifest(self.repo)            # manifest now lists newtool.py
        (self.repo / 'tools' / 'newtool.py').unlink()  # ...then the source vanishes
        with self.assertRaises(scaffold.ScaffoldError) as ctx:
            scaffold.run_update_tools(self.archive, self.repo)
        self.assertIn('missing', str(ctx.exception).lower())
        # the customized file was NOT moved to backup
        self.assertFalse((self.archive / '.plaintext-backup').exists())
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("MY EDIT")\n')

    def test_partial_failure_does_not_claim_success(self):
        # A per-file failure must not produce a success message or inflate the
        # summary counts (the output stays honest), and must surface the failure.
        _write(self.archive / '.fha' / 'tools' /'atool.py', 'print("MY EDIT")\n')  # customized
        _write(self.repo / 'tools' / 'atool.py', 'print("v2")\n')
        scaffold._write_manifest(self.repo)
        out, err = io.StringIO(), io.StringIO()
        with mock.patch('scaffold.shutil.move', side_effect=OSError('locked')):
            with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
                rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc, EXIT_WARNINGS)
        self.assertNotIn('has been backed up', out.getvalue())          # no false success
        self.assertIn('Done: 0 added, 0 updated, 0 backed up', out.getvalue())  # honest counts
        self.assertIn('could not be updated', err.getvalue())           # failure surfaced
        # the edit is intact (the move failed before touching it); nothing backed up
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("MY EDIT")\n')
        self.assertEqual(list((self.archive / '.plaintext-backup').rglob('atool.py')), [])

    def test_failed_update_keeps_edit_safe_on_retry(self):
        # Regression: a failed customized-file update must NOT record the edited
        # bytes as the installed baseline. If it did, the retry would see
        # disk == recorded, classify the file as pristine stock, and silently
        # overwrite the human's edit with no backup (data loss).
        _write(self.archive / '.fha' / 'tools' /'atool.py', 'print("MY EDIT")\n')
        _write(self.repo / 'tools' / 'atool.py', 'print("v2")\n')
        scaffold._write_manifest(self.repo)
        # Run 1: move fails.
        with mock.patch('scaffold.shutil.move', side_effect=OSError('locked')):
            with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
                self.assertEqual(scaffold.run_update_tools(self.archive, self.repo), EXIT_WARNINGS)
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("MY EDIT")\n')
        # Run 2: move works. The edit must be BACKED UP, not silently overwritten.
        with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
            self.assertEqual(scaffold.run_update_tools(self.archive, self.repo), EXIT_CLEAN)
        self.assertEqual((self.archive / '.fha' / 'tools' /'atool.py').read_text(encoding='utf-8'),
                         'print("v2")\n')
        backups = list((self.archive / '.plaintext-backup').rglob('atool.py'))
        self.assertEqual(len(backups), 1)
        self.assertEqual(backups[0].read_text(encoding='utf-8'), 'print("MY EDIT")\n')

    def test_failed_retired_move_is_retried_next_run(self):
        # A retired file whose move fails must stay recorded so the next run
        # re-detects and retries it (a successful move drops it from the stamp).
        retired = self.archive / '.fha' / 'tools' /'oldtool.py'
        _write(retired, 'print("old")\n')
        stamp = json.loads((self.archive / '.plaintext-version').read_text(encoding='utf-8'))
        stamp['files']['.fha/tools/oldtool.py'] = 'deadbeef'
        _write(self.archive / '.plaintext-version', json.dumps(stamp))
        with mock.patch('scaffold.shutil.move', side_effect=OSError('locked')):
            with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
                self.assertEqual(scaffold.run_update_tools(self.archive, self.repo), EXIT_WARNINGS)
        self.assertTrue(retired.exists())  # move failed, file still there
        # still recorded → still detectable as retired
        new_stamp = json.loads((self.archive / '.plaintext-version').read_text(encoding='utf-8'))
        self.assertIn('.fha/tools/oldtool.py', new_stamp['files'])
        # retry succeeds and moves it to backup
        with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
            self.assertEqual(scaffold.run_update_tools(self.archive, self.repo), EXIT_CLEAN)
        self.assertFalse(retired.exists())
        self.assertEqual(len(list((self.archive / '.plaintext-backup').rglob('oldtool.py'))), 1)

    def test_no_version_stamp_treats_existing_as_customized(self):
        # An archive whose tools were hand-copied (no install) still must not lose
        # a hand-edit on update.
        (self.archive / '.plaintext-version').unlink()
        _write(self.archive / '.fha' / 'tools' /'atool.py', 'print("HAND EDIT")\n')
        scaffold.run_update_tools(self.archive, self.repo)
        backups = list((self.archive / '.plaintext-backup').rglob('atool.py'))
        self.assertEqual(len(backups), 1)
        self.assertEqual(backups[0].read_text(encoding='utf-8'), 'print("HAND EDIT")\n')


class CmdErrorPathTest(unittest.TestCase):
    """The argparse bridges return friendly exit codes, never tracebacks."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self.repo = _make_fake_repo(self.tmp / 'repo')

    def tearDown(self):
        self._tmp.cleanup()

    def test_update_missing_repo(self):
        rc = scaffold._cmd_update_tools(argparse.Namespace(
            repo=None, root=str(self.tmp), dry_run=False, verbose=False))
        self.assertEqual(rc, EXIT_FAILURE)

    def test_update_not_an_archive(self):
        # root points at a folder with no fha.yaml; no auto-detect either.
        empty = self.tmp / 'not-an-archive'
        empty.mkdir()
        # find_archive_root walks up from CWD; force the no-root branch by passing
        # a root that exists but isn't an archive - _cmd uses the explicit root, so
        # update runs and fails to find a manifest? No: it runs against that root.
        # Instead drop --root and patch find_archive_root to None.
        with mock.patch('scaffold.find_archive_root', return_value=None):
            rc = scaffold._cmd_update_tools(argparse.Namespace(
                repo=str(self.repo), root=None, dry_run=False, verbose=False))
        self.assertEqual(rc, EXIT_FAILURE)

    def test_update_explicit_root_must_be_an_archive(self):
        # A mistyped --root (a real folder, but not an archive) must be refused
        # before any operating-layer file is written into it.
        not_arch = self.tmp / 'not-an-archive'
        not_arch.mkdir()
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            rc = scaffold._cmd_update_tools(argparse.Namespace(
                repo=str(self.repo), root=str(not_arch), dry_run=False, verbose=False))
        self.assertEqual(rc, EXIT_FAILURE)
        self.assertIn('does not look like an archive', err.getvalue())
        self.assertEqual(list(not_arch.iterdir()), [])  # nothing written

    def test_install_bad_repo_is_friendly_exit(self):
        rc = scaffold._cmd_install(argparse.Namespace(
            archive_path=str(self.tmp / 'arch'),
            repo=str(self.tmp / 'no-such-repo'), dry_run=False))
        self.assertEqual(rc, EXIT_FAILURE)


def _make_flat_archive(root: Path, *, with_stamp: bool = True) -> Path:
    """A pre-.fha archive: tools/, docs/, design/ at the root + a flat stamp.

    Note `serve.cmd`: a real pre-.fha archive's launcher names `tools\\fha.py`
    directly and knows nothing about a vendor folder, and `fha`/`fha.cmd` may not
    exist at all - which is exactly what moving tools/ breaks.
    """
    _write(root / 'fha.yaml', 'roots:\n  photos: photos\n  documents: documents\n')
    _write(root / 'SPEC.md', '# SPEC\n')          # root rulebook, stays put
    _write(root / 'CLAUDE.md', '# CLAUDE\n')      # root rulebook, stays put
    _write(root / 'serve.cmd', '@echo off\npy -3 tools\\fha.py serve %*\n')  # stale
    _write(root / 'tools' / 'fha.py', 'print("fha")\n')
    _write(root / 'tools' / 'sub' / 'x.py', 'x = 1\n')
    _write(root / 'docs' / 'guide.md', '# guide\n')        # stays at the root
    _write(root / 'design' / 'styles.css', 'body{}\n')      # vendored (in stamp)
    _write(root / 'design' / 'custom.css', '/* mine */\n')  # skeleton (NOT in stamp)
    _write(root / '.claude' / 'skills' / 's.md', '# skill\n')  # stays at root
    _write(root / 'people' / '.gitkeep', '')                # a record, untouched
    if with_stamp:
        stamp = {
            'manifest_version': '1', 'spec_version': '1.2',
            'installed': '2026-01-01T00:00:00',
            'files': {
                'tools/fha.py': 'aaa', 'tools/sub/x.py': 'bbb',
                'docs/guide.md': 'ccc', 'design/styles.css': 'ddd',
                'SPEC.md': 'eee', '.claude/skills/s.md': 'fff',
            },
        }
        _write(root / '.plaintext-version', json.dumps(stamp))
    return root


def _make_launcher_repo(root: Path) -> Path:
    """A stand-in workshop holding just the current root launchers."""
    _write(root / 'serve.cmd', '@echo off\nif exist ".fha\\tools\\fha.py" (echo new)\n')
    _write(root / 'fha.cmd', '@echo off\nrem .fha probe\n')
    _write(root / 'fha', '#!/bin/sh\n# .fha probe\n')
    return root


class MigrateLayoutTest(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.arc = _make_flat_archive(Path(self._tmp.name) / 'arc')
        self.launchers = _make_launcher_repo(Path(self._tmp.name) / 'workshop')

    def _migrate(self, **kw):
        kw.setdefault('repo_root', self.launchers)
        return scaffold.run_migrate_layout(self.arc, **kw)

    def tearDown(self):
        self._tmp.cleanup()

    def test_moves_subtrees_and_rekeys_stamp(self):
        rc = self._migrate()
        self.assertEqual(rc.exit_code, EXIT_CLEAN)
        # tools/docs/design now under .fha/ ...
        self.assertTrue((self.arc / '.fha' / 'tools' / 'fha.py').is_file())
        self.assertTrue((self.arc / '.fha' / 'tools' / 'sub' / 'x.py').is_file())
        self.assertTrue((self.arc / '.fha' / 'design' / 'styles.css').is_file())
        # ... custom.css rode along (it lives under design/) ...
        self.assertTrue((self.arc / '.fha' / 'design' / 'custom.css').is_file())
        # ... the flat copies are gone ...
        self.assertFalse((self.arc / 'tools').exists())
        self.assertFalse((self.arc / 'design').exists())
        # ... docs/ did NOT move: it is human-facing reading matter whose links
        # point at the root rulebooks and vice versa (see the manifest tests) ...
        self.assertTrue((self.arc / 'docs' / 'guide.md').is_file())
        self.assertFalse((self.arc / '.fha' / 'docs').exists())
        # ... rulebooks, skills, and records stayed at the root ...
        self.assertTrue((self.arc / 'SPEC.md').is_file())
        self.assertTrue((self.arc / '.claude' / 'skills' / 's.md').is_file())
        self.assertTrue((self.arc / 'people' / '.gitkeep').is_file())
        # ... and the stamp was re-keyed: vendored paths prefixed, others intact.
        stamp = json.loads((self.arc / '.plaintext-version').read_text(encoding='utf-8'))
        self.assertIn('.fha/tools/fha.py', stamp['files'])
        self.assertIn('.fha/design/styles.css', stamp['files'])
        self.assertNotIn('tools/fha.py', stamp['files'])
        self.assertIn('SPEC.md', stamp['files'])                 # root doc key intact
        self.assertIn('docs/guide.md', stamp['files'])           # docs key intact
        self.assertIn('.claude/skills/s.md', stamp['files'])     # skills key intact

    def test_dry_run_writes_nothing(self):
        before = sorted(p.relative_to(self.arc).as_posix()
                        for p in self.arc.rglob('*') if p.is_file())
        rc = self._migrate(dry_run=True)
        self.assertEqual(rc.exit_code, EXIT_CLEAN)
        after = sorted(p.relative_to(self.arc).as_posix()
                       for p in self.arc.rglob('*') if p.is_file())
        self.assertEqual(before, after)
        self.assertFalse((self.arc / '.fha').exists())

    def test_idempotent_noop_when_already_migrated(self):
        self._migrate()
        rc = self._migrate()  # second run
        self.assertEqual(rc.exit_code, EXIT_CLEAN)
        self.assertEqual(rc.data['moved'], 0)

    def test_refuses_ambiguous_half_migrated_state(self):
        _write(self.arc / '.fha' / 'tools' / 'fha.py', 'print("dup")\n')  # both exist
        with self.assertRaises(scaffold.ScaffoldError) as ctx:
            self._migrate()
        self.assertIn('refusing', str(ctx.exception).lower())
        self.assertTrue((self.arc / 'tools').exists())  # nothing moved

    def test_no_stamp_hand_copied_archive_still_moves(self):
        (self.arc / '.plaintext-version').unlink()
        rc = self._migrate()
        self.assertEqual(rc.exit_code, EXIT_CLEAN)
        self.assertTrue((self.arc / '.fha' / 'tools' / 'fha.py').is_file())
        self.assertFalse((self.arc / 'tools').exists())

    def test_refreshes_stale_and_missing_root_launchers(self):
        # A pre-.fha serve.cmd runs `tools\fha.py` by name and there is no CLI
        # shim beside it. Move tools/ without replacing them and double-clicking
        # serve.cmd stops working with no `fha` command to fall back on.
        rc = self._migrate()
        self.assertEqual(rc.exit_code, EXIT_CLEAN)
        self.assertEqual(rc.data['launchers_pending'], 0)
        serve = (self.arc / 'serve.cmd').read_text(encoding='utf-8')
        self.assertIn('.fha', serve)                       # refreshed, not stale
        self.assertTrue((self.arc / 'fha.cmd').is_file())  # installed, was absent
        self.assertTrue((self.arc / 'fha').is_file())      # POSIX shim too

    def test_reports_launchers_it_could_not_refresh(self):
        # Running from inside the archive: repo_root is the archive's own vendor
        # folder, which holds no launcher sources. Say so and name the fix rather
        # than leaving a silently broken serve.cmd behind.
        empty = Path(self._tmp.name) / 'empty-repo'
        empty.mkdir()
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            rc = scaffold.run_migrate_layout(self.arc, repo_root=empty)
        self.assertEqual(rc.exit_code, EXIT_CLEAN)
        self.assertTrue(rc.data['launchers_pending'])
        out = buf.getvalue()
        self.assertIn('serve.cmd', out)
        self.assertIn('update-tools', out)
        # The move itself still happened - the launcher is a follow-up, not a gate.
        self.assertTrue((self.arc / '.fha' / 'tools' / 'fha.py').is_file())

    def test_up_to_date_launcher_is_left_alone(self):
        _write(self.arc / 'serve.cmd', '@echo off\nrem .fha\\tools already probed\n')
        before = (self.arc / 'serve.cmd').read_text(encoding='utf-8')
        self._migrate()
        self.assertEqual((self.arc / 'serve.cmd').read_text(encoding='utf-8'), before)

    def test_names_capture_host_when_one_is_registered(self):
        # The browser's stored launcher holds an absolute <archive>/tools/fha.py;
        # the move invalidates it and doctor does not inspect it, so this run is
        # the only thing that can tell the owner.
        fake_host = self.arc / 'fake-host.json'
        _write(fake_host, '{}')
        buf = io.StringIO()
        with mock.patch.object(scaffold, '_capture_host_installed',
                               return_value=fake_host), \
                contextlib.redirect_stdout(buf):
            self._migrate()
        out = buf.getvalue()
        self.assertIn('capture --install-host', out)

    def test_dry_run_previews_launcher_and_capture_followups(self):
        fake_host = self.arc / 'fake-host.json'
        _write(fake_host, '{}')
        buf = io.StringIO()
        with mock.patch.object(scaffold, '_capture_host_installed',
                               return_value=fake_host), \
                contextlib.redirect_stdout(buf):
            self._migrate(dry_run=True)
        out = buf.getvalue()
        self.assertIn('serve.cmd', out)
        self.assertIn('capture --install-host', out)
        self.assertFalse((self.arc / '.fha').exists())     # still nothing written

    def test_malformed_stamp_files_value_does_not_traceback(self):
        # A hand-mangled stamp whose `files` is valid JSON but not an object used
        # to raise AttributeError from .items() - AFTER the folders had moved, so
        # the owner saw a traceback out of a mutating command.
        _write(self.arc / '.plaintext-version',
               json.dumps({'manifest_version': '1', 'files': ['tools/fha.py']}))
        rc = self._migrate()
        self.assertEqual(rc.exit_code, EXIT_CLEAN)
        self.assertTrue((self.arc / '.fha' / 'tools' / 'fha.py').is_file())
        stamp = json.loads((self.arc / '.plaintext-version').read_text(encoding='utf-8'))
        self.assertEqual(stamp['files'], {})   # re-stamped clean, not crashed

    def test_rollback_failure_names_stranded_paths(self):
        # Rolling back a half-done move can itself fail. Claiming "nothing was
        # left half-moved" then sends the owner to retry a command that cannot
        # succeed, against an archive that is genuinely split in two.
        real_move = scaffold.shutil.move
        calls = {'n': 0}

        def flaky(src, dst):
            calls['n'] += 1
            if calls['n'] == 1:
                return real_move(src, dst)     # tools/ moves
            raise OSError('boom')              # design/ fails, and so does undo

        with mock.patch.object(scaffold.shutil, 'move', side_effect=flaky):
            with self.assertRaises(scaffold.ScaffoldError) as ctx:
                self._migrate()
        msg = str(ctx.exception)
        self.assertIn('HALF-MIGRATED', msg)
        self.assertIn('tools', msg)
        self.assertNotIn('Nothing was left half-moved', msg)


class UpdateLayoutTransitionTest(unittest.TestCase):
    """update-tools across the flat -> .fha/ layout change."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        tmp = Path(self._tmp.name)
        self.repo = _make_fake_repo(tmp / 'repo')
        self.archive = tmp / 'arc'
        scaffold.run_install(self.archive, self.repo)

    def tearDown(self):
        self._tmp.cleanup()

    def _stamp(self):
        return json.loads(
            (self.archive / '.plaintext-version').read_text(encoding='utf-8'))

    def _regress_to_flat_custom_css(self, body='/* MY COLOURS */\n'):
        """Put the archive back in the pre-.fha state for the install-once seed."""
        new = self.archive / '.fha' / 'design' / 'custom.css'
        old = self.archive / 'design' / 'custom.css'
        _write(old, body)
        if new.exists():
            new.unlink()
        stamp = self._stamp()
        stamp['files'].pop('.fha/design/custom.css', None)
        stamp['files']['design/custom.css'] = 'whatever-was-installed'
        _write(self.archive / '.plaintext-version', json.dumps(stamp))
        return old, new

    def test_customized_stylesheet_survives_the_layout_change(self):
        # The regression this guards: the manifest no longer lists the flat path,
        # so it reads as RETIRED and goes to .plaintext-backup/ - and updates never
        # install skeleton entries, so nothing replaces it. The owner's styling
        # would simply be gone from the archive.
        old, new = self._regress_to_flat_custom_css()
        with contextlib.redirect_stdout(io.StringIO()):
            rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertEqual(rc.exit_code, EXIT_CLEAN)
        self.assertTrue(new.is_file(), 'the stylesheet must land at its new path')
        self.assertEqual(new.read_text(encoding='utf-8'), '/* MY COLOURS */\n')
        self.assertFalse(old.exists())
        # Not quarantined, and re-keyed in the stamp.
        backups = list((self.archive / '.plaintext-backup').rglob('custom.css')) \
            if (self.archive / '.plaintext-backup').exists() else []
        self.assertEqual(backups, [])
        self.assertIn('.fha/design/custom.css', self._stamp()['files'])
        self.assertNotIn('design/custom.css', self._stamp()['files'])

    def test_dry_run_previews_the_move_without_making_it(self):
        old, new = self._regress_to_flat_custom_css()
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            scaffold.run_update_tools(self.archive, self.repo, dry_run=True)
        self.assertIn('design/custom.css', buf.getvalue())
        self.assertTrue(old.is_file())      # untouched
        self.assertFalse(new.exists())
        # And the preview must not have called it retired - that is the very
        # outcome the real run avoids.
        self.assertNotIn('no longer part of the plaintext tools', buf.getvalue())

    def test_malformed_stamp_files_value_does_not_traceback(self):
        stamp = self._stamp()
        stamp['files'] = 'not-an-object'
        _write(self.archive / '.plaintext-version', json.dumps(stamp))
        with contextlib.redirect_stdout(io.StringIO()):
            rc = scaffold.run_update_tools(self.archive, self.repo)
        self.assertIn(rc.exit_code, (EXIT_CLEAN, EXIT_WARNINGS))
        self.assertIsInstance(self._stamp()['files'], dict)


if __name__ == '__main__':
    unittest.main()
