#!/usr/bin/env python3
"""
views.py — fha views: generate view files from the index.

  fha views timeline [P-id | --all-curated]
  fha views sources-index [P-id | --all-curated | --couple-folders]
  fha views draft-queue [P-id | --all-curated]
  fha views brackets      (not yet implemented)
  fha views tree          (not yet implemented)

ARCHITECTURE OVERVIEW
---------------------
Each view is a read-only projection of data that already exists in the
archive — it adds no new facts, only reorganises what the index knows.
All three implemented views follow the same pipeline:

  1. Open .cache/index.sqlite  (built by `fha index`; views never write it)
  2. Query claims / sources / persons tables
  3. Write one or more GENERATED-headed .md files back into the archive tree

The GENERATED header (see _gen_header) is the contract between views and lint:
lint rule W105 checks that generated companion files carry this exact header
so accidental hand-edits are caught on the next lint run.

Output files are "companion" files — they live alongside the profile they
describe and share its naming prefix:
    hartley__thomas_edward_P-de957bcda1.md          ← profile (hand-edited)
    hartley__thomas_edward_timeline_P-de957bcda1.md ← generated companion
    hartley__thomas_edward_sources-index_P-de957bcda1.md
    hartley__thomas_edward_draft-queue_P-de957bcda1.md

The couple-folder sources-index is the one exception: it has no P-id because
it describes a whole couple folder, not a single person (TOOLING §7).

SPEC §16 defines the companion kinds; TOOLING §7 defines each view's content.
"""

from __future__ import annotations

import argparse
import datetime
import re
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from _lib import (
    TOKEN_RE,       # regex that matches any [X-crockfordid] token in profile text
    EXIT_CLEAN,
    EXIT_FAILURE,
    EXIT_WARNINGS,
    find_archive_root,
    normalize_id,   # lower-cases IDs for consistent set/dict keying
    read_record,    # parses YAML front-matter + body from a .md file
)

# ── CODE MAP ──────────────────────────────────────────────────────────────────
#
#  Helpers (shared utilities)
#    _today, _gen_header          — GENERATED header text
#    _open_db, _resolve_root      — database / root resolution
#    _profile_path_for            — locate a person's .md profile file
#    _out_path_for                — build companion file path from profile path
#    _format_sid, _place_label    — formatting helpers
#    _curated_person_ids          — list all curated P-ids from index
#    _couple_folders              — identify curated couple folders + their members
#
#  Timeline view  (_generate_timeline)
#    _decade_from_edtf            — EDTF string → '### 1880s' decade header
#    _timeline_claim_line         — format one claim as a timeline bullet
#    _generate_timeline           — main generator: queries, groups, writes file
#
#  Sources-index view  (_generate_sources_index_*)
#    _source_ids_for_persons      — collect all source IDs linked to a person set
#    _write_sources_index         — shared writer (person and couple-folder both call this)
#    _generate_sources_index_person        — per-person sources-index
#    _generate_sources_index_couple_folder — couple-folder sources-index.md
#
#  Draft-queue view  (_generate_draft_queue)
#    _generate_draft_queue        — diff accepted sources against cited tokens
#
#  CLI wiring
#    _cmd_timeline, _cmd_sources_index, _cmd_draft_queue  — argparse handlers
#    _cmd_not_implemented, _cmd_views_help                — stubs / help
#    register           — called by fha.py to attach 'views' to the main parser
#    register_standalone, main    — used when running `python tools/views.py` directly
#
# ─────────────────────────────────────────────────────────────────────────────


# ── Helpers ───────────────────────────────────────────────────────────────────

def _today() -> str:
    return datetime.date.today().isoformat()


def _gen_header(subcommand: str) -> str:
    """
    Return the GENERATED header comment for a view file.

    The exact wording 'GENERATED by fha views {subcommand}' is checked by lint
    rule W105 — if you change this string, update the W105 pattern in lint.py
    as well, otherwise every existing generated file will be flagged as
    hand-edited on the next lint run.
    """
    return (
        f'<!-- GENERATED by fha views {subcommand} on {_today()}'
        ' — do not edit; regenerate instead -->\n\n'
    )


def _open_db(archive_root: Path) -> sqlite3.Connection | None:
    """
    Open the index database.
    Prints an error to stderr and returns None if the database is absent.
    """
    db_path = archive_root / '.cache' / 'index.sqlite'
    if not db_path.exists():
        print(
            'ERROR: .cache/index.sqlite not found — run `fha index` first '
            'then re-run this command.',
            file=sys.stderr,
        )
        return None
    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    return conn


def _resolve_root(args: argparse.Namespace) -> Path | None:
    """Resolve archive root from --root flag or auto-detection."""
    if getattr(args, 'root', None):
        return Path(args.root).resolve()
    detected = find_archive_root()
    if detected is None:
        print(
            'ERROR: cannot find archive root (no fha.yaml found). '
            'Use --root to specify.',
            file=sys.stderr,
        )
        return None
    return detected


def _profile_path_for(conn: sqlite3.Connection, person_id: str, archive_root: Path) -> Path | None:
    """Return the absolute path to the person's profile file, or None."""
    row = conn.execute(
        "SELECT path FROM person_files WHERE person_id = ? AND kind = 'profile'",
        (person_id,),
    ).fetchone()
    if not row:
        return None
    return archive_root / row['path']


def _out_path_for(profile_path: Path, kind: str, person_id: str) -> Path:
    """
    Construct the output path for a generated companion file.

    Companion files sit in the same directory as the profile and share its
    name prefix so they sort together in file explorers and travel together
    in git diffs:

        hartley__thomas_edward_P-de957bcda1.md          ← profile
        hartley__thomas_edward_timeline_P-de957bcda1.md ← this function's output

    The transformation: strip the trailing _{P-id}, append _{kind}_{P-id}.
    We strip first rather than just inserting before the suffix because the
    profile stem may already contain a prior-generation kind token that would
    produce a double-kind name on regeneration.
    """
    stem = profile_path.stem   # e.g. hartley__thomas_edward_P-de957bcda1
    # Strip trailing _{P-id} suffix (Crockford Base32 alphabet, case-insensitive)
    base = re.sub(r'_[PSCLH]-[0-9a-hjkmnp-tv-z]{10}$', '', stem, flags=re.I)
    # Filename convention: P-id uses uppercase type prefix
    pid_str = person_id[0].upper() + person_id[1:]   # p-xxx -> P-xxx
    return profile_path.parent / f'{base}_{kind}_{pid_str}.md'


def _format_sid(source_id: str) -> str:
    """Format a source ID as a citation token: s-xxx ->[S-xxx]."""
    return f'[{source_id[0].upper()}{source_id[1:]}]'


def _place_label(place_text: str | None, place_id: str | None,
                 conn: sqlite3.Connection) -> str | None:
    """
    Return a place display string for a claim line.
    Prefers place_text (as written in the source) over a place-table lookup.
    """
    if place_text:
        return place_text
    if place_id:
        row = conn.execute('SELECT name FROM places WHERE id = ?', (place_id,)).fetchone()
        if row and row['name']:
            return row['name']
    return None


def _curated_person_ids(conn: sqlite3.Connection) -> list[str]:
    """Return IDs of all persons with tier='curated'."""
    rows = conn.execute("SELECT id FROM persons WHERE tier = 'curated'").fetchall()
    return [r['id'] for r in rows]


def _couple_folders(conn: sqlite3.Connection, archive_root: Path) -> list[tuple[Path, list[str]]]:
    """
    Return [(folder_path, [person_ids])] for each curated couple folder.

    A "couple folder" is any directory directly under people/ that is not
    stubs/ or connections/ and contains at least one curated profile.
    (TOOLING §7: only folders with ≥1 curated person get a sources-index.md.)

    WHY TWO QUERIES: curated tier is the quality gate for deciding WHICH folders
    get a sources-index — we don't want one for every stub-only folder.  But the
    source union itself should cover everyone in the folder, including stub spouses
    and children.  A stub person may hold a unique source (e.g. an obituary for the
    spouse) that the biographer needs to see even though the stub hasn't been
    promoted to curated yet.  Using the curated-only set for the union would silently
    omit those sources.

    WHY OR ON LIKE: SQLite stores paths with the OS path separator.  On Windows the
    index contains backslashes; LIKE 'people/%' would miss them.  We match both to
    keep the function portable across platforms.
    """
    # Step 1: which folders contain at least one curated profile?
    curated_rows = conn.execute(
        """
        SELECT DISTINCT pf.path
        FROM person_files pf
        JOIN persons p ON pf.person_id = p.id
        WHERE pf.kind = 'profile' AND p.tier = 'curated'
          AND (pf.path LIKE 'people/%' OR pf.path LIKE 'people\\%')
        """
    ).fetchall()

    curated_folders: set[str] = set()
    for row in curated_rows:
        parts = Path(row['path']).parts   # ('people', '040 Thomas + Margaret', 'file.md')
        if len(parts) < 3:
            continue
        folder_name = parts[1]
        if folder_name.lower() not in ('stubs', 'connections'):
            curated_folders.add(folder_name)

    # Step 2: for each qualifying folder, collect ALL profiles (curated and stub).
    result = []
    for folder_name in sorted(curated_folders):
        all_rows = conn.execute(
            """
            SELECT pf.person_id
            FROM person_files pf
            WHERE pf.kind = 'profile'
              AND (pf.path LIKE ? OR pf.path LIKE ?)
            """,
            (f'people/{folder_name}/%', f'people\\{folder_name}\\%'),
        ).fetchall()
        person_ids = [r['person_id'] for r in all_rows]
        if person_ids:
            result.append((archive_root / 'people' / folder_name, person_ids))

    return result


# ── Timeline ──────────────────────────────────────────────────────────────────

def _decade_from_edtf(date_edtf: str | None) -> str | None:
    """
    Return a '### 1880s' header string for the decade of an EDTF date, or None.

    Extracts the year from date_edtf directly (e.g. '1840~' → 1840 → '### 1840s')
    rather than from date_min, which is widened for approximate dates and would
    give the wrong decade (e.g. '1840~' has date_min '1839-01-01').
    """
    if not date_edtf:
        return None
    # Handle interval A/B — use the start
    edtf = date_edtf.split('/')[0].strip()
    # Strip qualifiers: ~, ?, [..
    edtf = edtf.lstrip('[.').rstrip('~?]')
    try:
        year = int(edtf[:4])
        decade = (year // 10) * 10
        return f'### {decade}s'
    except (ValueError, IndexError):
        return None


def _timeline_claim_line(row: sqlite3.Row, conn: sqlite3.Connection) -> str:
    """Format one timeline line from a claims query row."""
    date_str = row['date_edtf'] or '(undated)'
    place = _place_label(row['place_text'], row['place_id'], conn)
    line = f'{date_str} — {row["type"]}: {row["value"]}'
    if place:
        line += f' @ {place}'
    line += f' {_format_sid(row["source_id"])}'
    return line


def _generate_timeline(
    conn: sqlite3.Connection, person_id: str, archive_root: Path
) -> Path | None:
    """
    Generate the timeline view for one person and write it to disk.

    Output structure (TOOLING §7):
      - One ### Decade section per decade of accepted/needs-review claims
      - Undated claims appear at the bottom of the dated section (ORDER BY puts
        NULL date_min last)
      - ## Unreviewed section at the end for suggested claims
        (suggested = AI-drafted, not yet accepted by a human reviewer)

    Returns the path written, or None if the person has no profile in the index.
    """
    profile_p = _profile_path_for(conn, person_id, archive_root)
    if not profile_p:
        print(f'WARNING: no profile found for {person_id} — skipped.', file=sys.stderr)
        return None

    name_row = conn.execute('SELECT name FROM persons WHERE id = ?', (person_id,)).fetchone()
    person_name = name_row['name'] if name_row else person_id

    # date_min is an ISO lower-bound used for sort order only; nulls sort last.
    # We fetch date_edtf separately for display and decade grouping (see _decade_from_edtf).
    main_rows = conn.execute(
        """
        SELECT DISTINCT c.date_edtf, c.date_min, c.type, c.value,
               c.place_id, c.place_text, c.source_id
        FROM claim_persons cp
        JOIN claims c ON cp.claim_id = c.id
        WHERE cp.person_id = ? AND c.status IN ('accepted', 'needs-review')
        ORDER BY
            CASE WHEN c.date_min IS NULL OR c.date_min = '' THEN 1 ELSE 0 END,
            c.date_min ASC
        """,
        (person_id,),
    ).fetchall()

    suggested_rows = conn.execute(
        """
        SELECT DISTINCT c.date_edtf, c.date_min, c.type, c.value,
               c.place_id, c.place_text, c.source_id
        FROM claim_persons cp
        JOIN claims c ON cp.claim_id = c.id
        WHERE cp.person_id = ? AND c.status = 'suggested'
        ORDER BY
            CASE WHEN c.date_min IS NULL OR c.date_min = '' THEN 1 ELSE 0 END,
            c.date_min ASC
        """,
        (person_id,),
    ).fetchall()

    out_path = _out_path_for(profile_p, 'timeline', person_id)

    # Accumulate rows into (decade_header, rows) sections before rendering.
    # We cannot emit section headers inline as we iterate because Markdown needs
    # a blank line BEFORE each ### header — we don't know whether a new section
    # is starting until we've already seen the first row of it.  Collecting first
    # lets us emit clean separators in a second pass without lookahead.
    sections: list[tuple[str | None, list[sqlite3.Row]]] = []
    current_decade: str | None = 'UNSET'   # sentinel; distinct from None (= undated)
    current_rows: list[sqlite3.Row] = []
    for row in main_rows:
        decade_hdr = _decade_from_edtf(row['date_edtf'])
        if decade_hdr != current_decade:
            if current_rows or current_decade != 'UNSET':
                sections.append((current_decade if current_decade != 'UNSET' else None, current_rows))
            current_decade = decade_hdr
            current_rows = []
        current_rows.append(row)
    if current_rows or current_decade != 'UNSET':
        sections.append((current_decade if current_decade != 'UNSET' else None, current_rows))

    parts: list[str] = [_gen_header('timeline'), f'# Timeline: {person_name}\n']

    for decade_hdr, rows in sections:
        if not rows:
            continue
        if decade_hdr:
            parts.append(f'\n{decade_hdr}\n\n')
        else:
            parts.append('\n')
        parts.append('\n'.join(f'- {_timeline_claim_line(r, conn)}' for r in rows))
        parts.append('\n')

    if suggested_rows:
        parts.append('\n## Unreviewed\n\n')
        parts.append('\n'.join(f'- {_timeline_claim_line(r, conn)}' for r in suggested_rows))
        parts.append('\n')

    out_path.write_text(''.join(parts), encoding='utf-8')
    return out_path


# ── Sources-index ─────────────────────────────────────────────────────────────

def _source_ids_for_persons(conn: sqlite3.Connection, person_ids: list[str]) -> list[str]:
    """
    Return distinct source IDs linked to any of the given persons.

    WHY UNION: the index tracks person-source links in two separate tables.
      - claim_persons → claims: covers sources that produced specific claims
        (e.g. a census record that generated a birth-year claim)
      - source_people: a direct person-source table for sources that are "about"
        a person even without specific extracted claims (e.g. a family bible
        that names someone but hasn't been processed into individual claims yet)
    The UNION catches both so the sources-index is complete.
    """
    if not person_ids:
        return []
    placeholders = ','.join('?' * len(person_ids))
    rows = conn.execute(
        f"""
        SELECT DISTINCT c.source_id
        FROM claim_persons cp
        JOIN claims c ON cp.claim_id = c.id
        WHERE cp.person_id IN ({placeholders})
        UNION
        SELECT DISTINCT source_id
        FROM source_people
        WHERE person_id IN ({placeholders})
        """,
        person_ids + person_ids,
    ).fetchall()
    return [r[0] for r in rows]


def _write_sources_index(
    conn: sqlite3.Connection,
    source_ids: list[str],
    out_path: Path,
    title: str,
    subcommand: str = 'sources-index',
) -> None:
    """
    Write a sources-index .md file for the given source IDs.

    Shared by both the per-person and couple-folder generators so the output
    format stays identical regardless of scope.  Callers supply the title and
    output path; everything else is derived from the index.
    Sources are grouped by source_type (census, newspaper, other, …) and sorted
    alphabetically within each group.
    """
    if not source_ids:
        out_path.write_text(
            _gen_header(subcommand) + f'# {title}\n\n*(No sources found.)*\n',
            encoding='utf-8',
        )
        return

    placeholders = ','.join('?' * len(source_ids))
    rows = conn.execute(
        f"""
        SELECT id, title, source_type, path
        FROM sources
        WHERE id IN ({placeholders})
        ORDER BY source_type, title
        """,
        source_ids,
    ).fetchall()

    # Group by source_type
    by_type: dict[str, list[sqlite3.Row]] = {}
    for row in rows:
        st = row['source_type'] or 'other'
        by_type.setdefault(st, []).append(row)

    lines: list[str] = [_gen_header(subcommand), f'# {title}\n']

    for source_type in sorted(by_type.keys()):
        lines.append(f'\n## {source_type}\n')
        for row in by_type[source_type]:
            sid_token = _format_sid(row['id'])
            lines.append(f'\n**{row["title"]}** {sid_token}  \n')
            lines.append(f'  {row["path"]}\n')

    out_path.write_text(''.join(lines), encoding='utf-8')


def _generate_sources_index_person(
    conn: sqlite3.Connection, person_id: str, archive_root: Path
) -> Path | None:
    """Generate the per-person sources-index. Returns the path written, or None."""
    profile_p = _profile_path_for(conn, person_id, archive_root)
    if not profile_p:
        print(f'WARNING: no profile found for {person_id} — skipped.', file=sys.stderr)
        return None

    name_row = conn.execute('SELECT name FROM persons WHERE id = ?', (person_id,)).fetchone()
    person_name = name_row['name'] if name_row else person_id

    source_ids = _source_ids_for_persons(conn, [person_id])
    out_path = _out_path_for(profile_p, 'sources-index', person_id)
    _write_sources_index(conn, source_ids, out_path, f'Sources: {person_name}')
    return out_path


def _generate_sources_index_couple_folder(
    conn: sqlite3.Connection,
    folder_path: Path,
    person_ids: list[str],
) -> Path:
    """
    Generate the couple-folder sources-index.md at the folder root.
    Returns the path written.
    """
    source_ids = _source_ids_for_persons(conn, person_ids)
    out_path = folder_path / 'sources-index.md'
    folder_name = folder_path.name
    _write_sources_index(
        conn, source_ids, out_path, f'Sources: {folder_name}',
    )
    return out_path


# ── Draft-queue ───────────────────────────────────────────────────────────────

def _generate_draft_queue(
    conn: sqlite3.Connection, person_id: str, archive_root: Path
) -> Path | None:
    """
    Generate the draft-queue view for one person and write it to disk.

    Purpose: the draft-queue is the biographer's to-do list.  It answers the
    question "which accepted sources have I not yet cited in the profile prose?"
    A source appears in the queue when the index has accepted claims from it
    but the profile body contains no [S-id] citation token for it.

    HOW "CITED" IS DETERMINED: we scan the profile body (not the YAML front-
    matter) for [S-xxx] tokens using TOKEN_RE.  The body is where the summary
    block and biography prose live.  If an S-id token appears anywhere in the
    body, that source is considered cited and omitted from the queue.

    HOW THE DIFF WORKS:
      accepted_sids  = {source_ids with ≥1 accepted claim for this person}
      cited_sids     = {S-ids found as [S-xxx] tokens in the profile body}
      uncited_sids   = accepted_sids - cited_sids   ← the queue

    The queue lists each uncited source with its accepted claims so the
    biographer can see what facts still need to be woven into the prose.
    Returns the path written, or None if the person has no profile in the index.
    """
    profile_p = _profile_path_for(conn, person_id, archive_root)
    if not profile_p:
        print(f'WARNING: no profile found for {person_id} — skipped.', file=sys.stderr)
        return None

    name_row = conn.execute('SELECT name FROM persons WHERE id = ?', (person_id,)).fetchone()
    person_name = name_row['name'] if name_row else person_id

    rec = read_record(profile_p)
    body = rec['body']
    # TOKEN_RE matches [X-crockfordid]; we filter to S- only (source citations)
    cited_sids: set[str] = set(
        normalize_id(m.group(1)) for m in TOKEN_RE.finditer(body)
        if m.group(1).lower().startswith('s-')
    )

    accepted_rows = conn.execute(
        """
        SELECT DISTINCT c.source_id, c.type, c.value, c.date_edtf
        FROM claim_persons cp
        JOIN claims c ON cp.claim_id = c.id
        WHERE cp.person_id = ? AND c.status = 'accepted'
        ORDER BY c.source_id, c.date_min
        """,
        (person_id,),
    ).fetchall()

    accepted_sids: set[str] = {normalize_id(r['source_id']) for r in accepted_rows}
    uncited_sids = accepted_sids - cited_sids

    out_path = _out_path_for(profile_p, 'draft-queue', person_id)

    lines: list[str] = [_gen_header('draft-queue'), f'# Draft Queue: {person_name}\n']

    if not uncited_sids:
        lines.append('\nAll accepted claims are cited in the profile.\n')
        out_path.write_text(''.join(lines), encoding='utf-8')
        return out_path

    # Fetch source metadata for uncited sources
    placeholders = ','.join('?' * len(uncited_sids))
    source_rows = conn.execute(
        f"""
        SELECT id, title, source_type
        FROM sources
        WHERE id IN ({placeholders})
        ORDER BY source_type, title
        """,
        list(uncited_sids),
    ).fetchall()

    # Index claims by source_id for quick lookup
    claims_by_source: dict[str, list[sqlite3.Row]] = {}
    for row in accepted_rows:
        sid = normalize_id(row['source_id'])
        if sid in uncited_sids:
            claims_by_source.setdefault(sid, []).append(row)

    lines.append(
        f'\n{len(uncited_sids)} source(s) with accepted claims not yet cited in the profile:\n'
    )

    for src in source_rows:
        sid = normalize_id(src['id'])
        sid_token = _format_sid(src['id'])
        lines.append(f'\n**{src["title"]}** {sid_token}\n')
        for claim_row in claims_by_source.get(sid, []):
            date_edtf = claim_row['date_edtf']
            date_str = f'({date_edtf})' if date_edtf else '(undated)'
            lines.append(f'  - {claim_row["type"]}: {claim_row["value"]} {date_str}\n')

    out_path.write_text(''.join(lines), encoding='utf-8')
    return out_path


# ── CLI command handlers ──────────────────────────────────────────────────────

def _cmd_timeline(args: argparse.Namespace) -> int:
    archive_root = _resolve_root(args)
    if archive_root is None:
        return EXIT_FAILURE

    conn = _open_db(archive_root)
    if conn is None:
        return EXIT_FAILURE

    try:
        if getattr(args, 'all_curated', False):
            person_ids = _curated_person_ids(conn)
            if not person_ids:
                print('No curated persons found in index.')
                return EXIT_CLEAN
            count = 0
            for pid in person_ids:
                out = _generate_timeline(conn, pid, archive_root)
                if out:
                    print(f'  timeline ->{out.relative_to(archive_root)}')
                    count += 1
            print(f'Generated {count} timeline file(s).')
            return EXIT_CLEAN

        person_id = getattr(args, 'person_id', None)
        if not person_id:
            print('ERROR: provide a P-id or --all-curated.', file=sys.stderr)
            return EXIT_FAILURE

        pid = normalize_id(person_id)
        out = _generate_timeline(conn, pid, archive_root)
        if out:
            print(f'  timeline ->{out.relative_to(archive_root)}')
            return EXIT_CLEAN
        return EXIT_WARNINGS

    finally:
        conn.close()


def _cmd_sources_index(args: argparse.Namespace) -> int:
    archive_root = _resolve_root(args)
    if archive_root is None:
        return EXIT_FAILURE

    conn = _open_db(archive_root)
    if conn is None:
        return EXIT_FAILURE

    try:
        all_curated = getattr(args, 'all_curated', False)
        couple_folders_only = getattr(args, 'couple_folders', False)

        if all_curated or couple_folders_only:
            count = 0
            if not couple_folders_only:
                # Per-person files for all curated persons
                for pid in _curated_person_ids(conn):
                    out = _generate_sources_index_person(conn, pid, archive_root)
                    if out:
                        print(f'  sources-index ->{out.relative_to(archive_root)}')
                        count += 1

            # Couple-folder sources-index.md files
            for folder_path, person_ids in _couple_folders(conn, archive_root):
                out = _generate_sources_index_couple_folder(conn, folder_path, person_ids)
                print(f'  sources-index ->{out.relative_to(archive_root)}')
                count += 1

            print(f'Generated {count} sources-index file(s).')
            return EXIT_CLEAN

        person_id = getattr(args, 'person_id', None)
        if not person_id:
            print('ERROR: provide a P-id, --all-curated, or --couple-folders.', file=sys.stderr)
            return EXIT_FAILURE

        pid = normalize_id(person_id)
        out = _generate_sources_index_person(conn, pid, archive_root)
        if out:
            print(f'  sources-index ->{out.relative_to(archive_root)}')
            return EXIT_CLEAN
        return EXIT_WARNINGS

    finally:
        conn.close()


def _cmd_draft_queue(args: argparse.Namespace) -> int:
    archive_root = _resolve_root(args)
    if archive_root is None:
        return EXIT_FAILURE

    conn = _open_db(archive_root)
    if conn is None:
        return EXIT_FAILURE

    try:
        if getattr(args, 'all_curated', False):
            person_ids = _curated_person_ids(conn)
            if not person_ids:
                print('No curated persons found in index.')
                return EXIT_CLEAN
            count = 0
            for pid in person_ids:
                out = _generate_draft_queue(conn, pid, archive_root)
                if out:
                    print(f'  draft-queue ->{out.relative_to(archive_root)}')
                    count += 1
            print(f'Generated {count} draft-queue file(s).')
            return EXIT_CLEAN

        person_id = getattr(args, 'person_id', None)
        if not person_id:
            print('ERROR: provide a P-id or --all-curated.', file=sys.stderr)
            return EXIT_FAILURE

        pid = normalize_id(person_id)
        out = _generate_draft_queue(conn, pid, archive_root)
        if out:
            print(f'  draft-queue ->{out.relative_to(archive_root)}')
            return EXIT_CLEAN
        return EXIT_WARNINGS

    finally:
        conn.close()


def _cmd_not_implemented(args: argparse.Namespace) -> int:
    subcmd = getattr(args, 'views_command', '?')
    print(f'fha views {subcmd}: not yet implemented.')
    return EXIT_CLEAN


def _cmd_views_help(args: argparse.Namespace) -> int:
    # Retrieve the views sub-parser and print its help via the stored reference
    parser = getattr(args, '_views_parser', None)
    if parser:
        parser.print_help()
    else:
        print('Usage: fha views <subcommand> [options]')
        print('Subcommands: timeline, sources-index, draft-queue, brackets, tree')
    return EXIT_CLEAN


# ── Parser registration ───────────────────────────────────────────────────────

def register(subs: argparse._SubParsersAction) -> argparse.ArgumentParser:
    """Register the `views` subcommand group on the given subparsers action."""
    views_p = subs.add_parser(
        'views',
        help='Generate view files from the index (timeline, sources-index, draft-queue, …).',
        description='Generate GENERATED-headed .md view files from the index.',
    )
    views_p.set_defaults(func=_cmd_views_help)

    vsubs = views_p.add_subparsers(dest='views_command', metavar='SUBCOMMAND')

    # ── timeline ──────────────────────────────────────────────────────────────
    tl = vsubs.add_parser(
        'timeline',
        help='Generate per-person timeline view.',
        description=(
            'Generate {name}_timeline_{P-id}.md in the person\'s folder.\n'
            'Requires a fresh .cache/index.sqlite (run `fha index` first).'
        ),
    )
    tl.add_argument('person_id', nargs='?', metavar='P-id',
                    help='Person to generate for.')
    tl.add_argument('--all-curated', action='store_true',
                    help='Generate for every curated person.')
    tl.add_argument('--root', metavar='PATH', help='Archive root (auto-detected if omitted).')
    tl.set_defaults(func=_cmd_timeline)

    # ── sources-index ─────────────────────────────────────────────────────────
    si = vsubs.add_parser(
        'sources-index',
        help='Generate per-person (and optionally couple-folder) sources-index view.',
        description=(
            'Generate {name}_sources-index_{P-id}.md per person, and/or\n'
            'sources-index.md per curated couple folder.\n'
            'Requires a fresh .cache/index.sqlite (run `fha index` first).'
        ),
    )
    si.add_argument('person_id', nargs='?', metavar='P-id',
                    help='Person to generate for.')
    si.add_argument('--all-curated', action='store_true',
                    help='Generate per-person and couple-folder files for all curated persons.')
    si.add_argument('--couple-folders', action='store_true',
                    help='Generate sources-index.md in every curated couple folder.')
    si.add_argument('--root', metavar='PATH', help='Archive root (auto-detected if omitted).')
    si.set_defaults(func=_cmd_sources_index)

    # ── draft-queue ───────────────────────────────────────────────────────────
    dq = vsubs.add_parser(
        'draft-queue',
        help='Generate per-person draft-queue (uncited-claim backlog) view.',
        description=(
            'Generate {name}_draft-queue_{P-id}.md in the person\'s folder.\n'
            'Requires a fresh .cache/index.sqlite (run `fha index` first).'
        ),
    )
    dq.add_argument('person_id', nargs='?', metavar='P-id',
                    help='Person to generate for.')
    dq.add_argument('--all-curated', action='store_true',
                    help='Generate for every curated person.')
    dq.add_argument('--root', metavar='PATH', help='Archive root (auto-detected if omitted).')
    dq.set_defaults(func=_cmd_draft_queue)

    # ── brackets (stub) ───────────────────────────────────────────────────────
    br = vsubs.add_parser(
        'brackets',
        help='Refresh couple-folder bracket lists (not yet implemented).',
    )
    br.add_argument('--root', metavar='PATH', help='Archive root (auto-detected if omitted).')
    br.add_argument('--fix', action='store_true', help='Apply fixes (not yet implemented).')
    br.set_defaults(func=_cmd_not_implemented)

    # ── tree (stub) ───────────────────────────────────────────────────────────
    tr = vsubs.add_parser(
        'tree',
        help='Generate relationship tree view (not yet implemented).',
    )
    tr.add_argument('person_id', nargs='?', metavar='P-id')
    tr.add_argument('--mode', choices=['ancestors', 'descendants', 'fan'])
    tr.add_argument('--root', metavar='PATH', help='Archive root (auto-detected if omitted).')
    tr.set_defaults(func=_cmd_not_implemented)

    # Store a back-reference so _cmd_views_help can print the right help text
    views_p.set_defaults(_views_parser=views_p)

    return views_p


# ── Standalone entry point ────────────────────────────────────────────────────

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog='fha views',
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument('--root', metavar='PATH',
                        help='Archive root (auto-detected if omitted).')
    subs = parser.add_subparsers(dest='views_command', metavar='SUBCOMMAND')
    register_standalone(subs)

    args = parser.parse_args(argv)
    if not args.views_command:
        parser.print_help()
        return EXIT_CLEAN

    return args.func(args) or EXIT_CLEAN


def register_standalone(subs: argparse._SubParsersAction) -> None:
    """Register subcommands directly (for standalone python tools/views.py invocation)."""
    for name, help_text, func, extra in [
        ('timeline',      'Generate per-person timeline view.',           _cmd_timeline,       _add_person_curated_args),
        ('sources-index', 'Generate per-person sources-index view.',      _cmd_sources_index,  _add_si_args),
        ('draft-queue',   'Generate per-person draft-queue view.',        _cmd_draft_queue,    _add_person_curated_args),
        ('brackets',      'Refresh couple-folder bracket lists (stub).',  _cmd_not_implemented, None),
        ('tree',          'Generate relationship tree view (stub).',      _cmd_not_implemented, None),
    ]:
        p = subs.add_parser(name, help=help_text)
        p.add_argument('--root', metavar='PATH', help='Archive root (auto-detected if omitted).')
        if extra:
            extra(p)
        p.set_defaults(func=func)


def _add_person_curated_args(p: argparse.ArgumentParser) -> None:
    p.add_argument('person_id', nargs='?', metavar='P-id')
    p.add_argument('--all-curated', action='store_true')


def _add_si_args(p: argparse.ArgumentParser) -> None:
    p.add_argument('person_id', nargs='?', metavar='P-id')
    p.add_argument('--all-curated', action='store_true')
    p.add_argument('--couple-folders', action='store_true')


if __name__ == '__main__':
    sys.exit(main())
